'use server';
import {z} from 'zod';
import {getSessionProfile} from '@/lib/auth/session';
import {createServerSupabaseClient} from '@/lib/supabase/server';
import {revalidatePath} from 'next/cache';
import {clientDraftSource,type ClientDraft} from '@/lib/office/client-drafts';
async function access(){const session=await getSessionProfile();if(!session||session.profile.role!=='admin')throw new Error('Finance admin access required');return createServerSupabaseClient();}
const inputSchema=z.object({id:z.string().uuid(),clientId:z.string().uuid(),from:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),to:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),issue:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),due:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),gst:z.enum(['exclusive','none'])});
export async function prepareClientDraft(input:z.infer<typeof inputSchema>){const db=await access();const parsed=inputSchema.safeParse(input);if(!parsed.success)return {ok:false,message:'Check the client, dates and GST treatment.'};const v=parsed.data;const {error}=await db.rpc('office_prepare_client_draft',{p_id:v.id,p_client:v.clientId,p_from:v.from,p_to:v.to,p_issue:v.issue,p_due:v.due,p_gst:v.gst});if(error)return {ok:false,message:error.code==='P0001'?error.message:'Draft could not be prepared. Check the dates and retry.'};revalidatePath('/office');return {ok:true,message:'Draft prepared from your recorded billable hours and agreed client rates. Review the calculation before approving.'};}
export async function listClientDrafts(){const db=await access();const result:ClientDraft[]=[];for(let start=0;;start+=500){const {data,error}=await db.from('office_client_drafts').select('*').order('created_at',{ascending:false}).order('id').range(start,start+499);if(error)throw new Error('Client invoice drafts unavailable');for(const row of data??[]){const source=clientDraftSource.parse(row.source);result.push({...row,source} as ClientDraft);}if((data?.length??0)<500)break;}return result;}
export async function approveClientDraft(id:string,digest:string){const db=await access();const {data,error}=await db.rpc('office_approve_client_draft',{p_id:id,p_digest:digest});if(error)return {ok:false,message:error.code==='P0001'?error.message:'Approval could not be confirmed. Refresh before retrying.'};revalidatePath('/office');return {ok:true,message:`${data} approved. Work records are now locked against duplicate invoicing. No email has been sent.`};}
export async function cancelClientDraft(id:string,reason:string,neverSent:boolean){const db=await access();const {error}=await db.rpc('office_cancel_client_draft',{p_id:id,p_reason:reason,p_unsent:neverSent});if(error)return {ok:false,message:error.code==='P0001'?error.message:'Cancellation could not be confirmed. Refresh before retrying.'};revalidatePath('/office');return {ok:true,message:'Cancelled with history preserved. Its work records are available for a corrected draft.'};}
