import {describe,it,expect} from 'vitest';
import {generateOfficeClientInvoicePdf,generateOfficeWorkSummaryPdf,type OfficeInvoicePdfInput} from '../lib/invoices/pdf';
const input:OfficeInvoicePdfInput={number:'Draft-example',status:'draft',clientName:'Example Client',clientAbn:'',issueDate:'2026-09-26',dueDate:'2026-10-10',periodStart:'2026-09-14',periodEnd:'2026-09-20',subtotalCents:80000,gstCents:8000,totalCents:88000,gstMode:'exclusive',rows:[{workDate:'2026-09-14',siteName:'Example Site',fullName:'Example Person',summaryName:'Example',actualHours:8,clientHours:10}]};
describe('Office invoice and work summary PDFs',()=>{
 it('renders a draft with GST and no invented tonnage',()=>{const text=generateOfficeClientInvoicePdf(input).toString();expect(text).toContain('DRAFT - NOT ISSUED');expect(text).toContain('$880.00');expect(text).not.toContain('physical production delivered');});
 it('uses frozen client hours and dated rates for invoice billing groups',()=>{const rows=[{...input.rows[0],rateCents:8000,amountCents:80000},{...input.rows[0],workDate:'2026-09-15',actualHours:8,clientHours:12,rateCents:9000,amountCents:108000}];const text=generateOfficeClientInvoicePdf({...input,subtotalCents:188000,gstCents:18800,totalCents:206800,rows}).toString();expect(text).toContain('$800.00');expect(text).toContain('$900.00');expect(text).toContain('1.200');expect(text).toContain('$2,068.00');expect(text).not.toContain('Example Person');expect(()=>generateOfficeClientInvoicePdf({...input,rows})).toThrow('frozen subtotal');});
 it('keeps amounts/rates out of the work summary',()=>{const text=generateOfficeWorkSummaryPdf(input).toString();expect(text).toContain('Hours');expect(text).not.toContain('Example Client');expect(text).not.toContain('Draft-example');expect(text).not.toContain('$');expect(text).not.toContain('800.00');});
 it('never exposes legal names or falls back when a short name is absent',()=>{const text=generateOfficeWorkSummaryPdf(input).toString();expect(text).not.toContain('Example Person');expect(()=>generateOfficeWorkSummaryPdf({...input,rows:input.rows.map(r=>({...r,summaryName:undefined}))})).toThrow('Short name missing');});
 it('paginates long summaries',()=>{const text=generateOfficeWorkSummaryPdf({...input,rows:Array.from({length:70},()=>({...input.rows[0],siteName:'A longer construction site name with several sections'}))}).toString();expect(text).toContain('Page 2');});
 it('preserves unsupported names by refusing a corrupt export',()=>expect(()=>generateOfficeWorkSummaryPdf({...input,rows:[{...input.rows[0],summaryName:'Батбаяр'}]})).toThrow('Unicode PDF font'));
});
