'use client';
import {useEffect,useState,useTransition,useRef} from 'react';
import {useRouter} from 'next/navigation';
import {submitAssistantTask,listAssistantTasks,applyAssistantTask} from '@/app/actions/assistant';
import {assistantResponse,type AssistantTask} from '@/lib/office/assistant';
export function AssistantChat({navigate,clients}:{navigate:(section:string)=>void;clients:{id:string;name:string}[]}){
 const router=useRouter(),[tasks,setTasks]=useState<AssistantTask[]>([]),[prompt,setPrompt]=useState(''),[notice,setNotice]=useState(''),[pending,start]=useTransition();const id=useRef<string>('');
 async function refresh(){try{setTasks(await listAssistantTasks() as AssistantTask[]);}catch{setNotice('Conversation could not be loaded. Try Refresh.');}}
 useEffect(()=>{void refresh();const timer=setInterval(()=>void refresh(),10000);return()=>clearInterval(timer);},[]);
 function send(){if(!id.current)id.current=crypto.randomUUID();start(async()=>{try{const result=await submitAssistantTask(id.current,prompt);setNotice(result.message);if(result.ok){setPrompt('');id.current='';await refresh();}}catch{setNotice('Could not confirm your request. Retry with the same text.');}});}
 return <section className="ember-panel"><h2>Office Manager</h2><p className="muted">Ask about your company records, or ask me to prepare a new client, site or contractor. Review the proposed details and tap Create record to save.</p><p className="ember-footnote">The assistant runs on your Mac. Requests wait while it is asleep or offline. Email sending, live inbox checks and invoice generation are not connected to this chat yet.</p><div className="ember-chips"><button onClick={()=>{setPrompt('Өнөөдрийн ажлын бүртгэлийг товч харуул.');id.current='';}}>Today’s records</button><button onClick={()=>{setPrompt('Шинэ клайнт бүртгэхэд ямар мэдээлэл хэрэгтэй вэ?');id.current='';}}>New client</button><button onClick={()=>{setPrompt('Контракторуудын бүртгэлийг харуул.');id.current='';}}>Contractors</button><button onClick={()=>void refresh()}>Refresh</button></div>
 <div aria-live="polite">{tasks.map(task=>{const parsed=assistantResponse.safeParse(task.response),r=parsed.success?parsed.data:null;return <article className="ember-person" key={task.id}><p className="eyebrow">YOU</p><p style={{whiteSpace:'pre-wrap'}}>{task.prompt}</p><p className="eyebrow">OFFICE MANAGER</p>{task.status==='queued'?<p className="muted">Waiting for your Mac…</p>:task.status==='running'?<p className="muted">Working on your request…</p>:r?<><p style={{whiteSpace:'pre-wrap'}}>{r.reply}</p>{r.action!=='none'&&<div className="ember-panel"><p><strong>{r.action.replaceAll('_',' ')}</strong></p><p>{r.name}</p><p>{r.email} {r.phone}</p>{r.abn&&<p>ABN {r.abn}</p>}{r.action==='create_site'&&<p>Client: {clients.find(c=>c.id===r.clientId)?.name??'Client unavailable — review before saving'}</p>}{r.address&&<p>{r.address}</p>}{r.action==='create_client'&&<p>Payment terms: 14 days · Active</p>}{r.action==='create_contractor'&&<p>{r.group==='regular'?'Regular contractor':'Occasional contractor'} · Active</p>}{task.applied_id?<p>Created ✓</p>:<button disabled={pending} onClick={()=>start(async()=>{try{const result=await applyAssistantTask(task.id);setNotice(result.message);if(result.ok){await refresh();router.refresh();}}catch{setNotice('Could not confirm the save. Refresh before retrying.');}})}>Create record</button>}</div>}{r.section!=='none'&&<button className="ember-link" onClick={()=>navigate(r.section)}>Open related section →</button>}</>:<p className="error">Assistant could not complete this request. Check the Mac connection and try again.</p>}</article>;})}</div>
 <form onSubmit={e=>{e.preventDefault();send();}}><label htmlFor="office-request">Your request</label><textarea id="office-request" rows={4} maxLength={4000} placeholder="Tell your office manager what you need…" value={prompt} disabled={pending} onChange={e=>{setPrompt(e.target.value);id.current='';}}/><button className="ember-primary" disabled={pending||!prompt.trim()} type="submit">{pending?'Sending…':'Send request'}</button></form>{notice&&<p className="ember-notice" role="status">{notice}</p>}</section>;
}
