'use client';
import {InvoiceEmail} from './invoice-email';
import {useEffect,useRef,useState,useTransition} from 'react';
import {useRouter} from 'next/navigation';
import {prepareClientDraft,listClientDrafts,approveClientDraft,cancelClientDraft} from '@/app/actions/client-drafts';
import type {ClientDraft} from '@/lib/office/client-drafts';
import {addIsoDays} from '@/lib/operations/dates';
const money=(n:number)=>new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD'}).format(n/100);
export function ClientDrafts({clients,today,from,to}:{clients:{id:string;name:string;active:boolean}[];today:string;from:string;to:string}){
 const [drafts,setDrafts]=useState<ClientDraft[]>([]),[client,setClient]=useState(''),[startDay,setStart]=useState(from),[endDay,setEnd]=useState(to),[issue,setIssue]=useState(today),[due,setDue]=useState(addIsoDays(today,14)),[gst,setGst]=useState<'exclusive'|'none'>('exclusive'),[message,setMessage]=useState(''),[pending,transition]=useTransition();const id=useRef('');
 async function refresh(){try{setDrafts(await listClientDrafts());}catch{setMessage('Could not load invoice drafts. Refresh before continuing.');}}
 useEffect(()=>{void refresh();},[]);
 const edit=(change:()=>void)=>{id.current='';change();};
 return <section className="ember-panel"><h2>Prepare client invoice</h2><p className="muted">Your recorded client billable hours and agreed client rates produce the draft. Actual work and contractor payable hours stay separate.</p><form onSubmit={e=>{e.preventDefault();if(!id.current)id.current=crypto.randomUUID();transition(async()=>{try{const r=await prepareClientDraft({id:id.current,clientId:client,from:startDay,to:endDay,issue,due,gst});setMessage(r.message);if(r.ok){id.current='';await refresh();}}catch{setMessage('Could not confirm draft creation. Retry with the same details.');}});}}><div className="ember-adjust"><label>Client<select required value={client} disabled={pending} onChange={e=>edit(()=>setClient(e.target.value))}><option value="">Select client</option>{clients.filter(c=>c.active).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Work from<input required type="date" value={startDay} max={today} disabled={pending} onChange={e=>edit(()=>setStart(e.target.value))}/></label><label>Work to<input required type="date" value={endDay} min={startDay} max={today} disabled={pending} onChange={e=>edit(()=>setEnd(e.target.value))}/></label><label>Issue date<input required type="date" value={issue} min={endDay} max={today} disabled={pending} onChange={e=>edit(()=>setIssue(e.target.value))}/></label><label>Due date<input required type="date" value={due} min={issue} disabled={pending} onChange={e=>edit(()=>setDue(e.target.value))}/></label><label>GST treatment<select value={gst} disabled={pending} onChange={e=>edit(()=>setGst(e.target.value as 'exclusive'|'none'))}><option value="exclusive">Add 10% GST to agreed rates</option><option value="none">No GST charged</option></select></label></div><button className="ember-primary" type="submit" disabled={pending||!client}>{pending?'Preparing…':'Prepare draft'}</button></form><p className="ember-footnote">Office rates are entered excluding GST. Due date defaults to 14 days; check your client’s agreed terms. Missing rates or locked work records stop preparation.</p>{message&&<p role="status">{message}</p>}<button className="ember-link" onClick={()=>void refresh()}>Refresh drafts</button>
 <h2>Invoice drafts & approvals</h2>{drafts.length===0&&<p className="muted">No new invoice drafts yet.</p>}{drafts.map(d=><DraftCard key={d.id} draft={d} refresh={refresh}/>)}<p className="ember-footnote">Email delivery requires your review of each recipient, message and attachment, plus a connected Mac with Gmail sending permission.</p></section>;
}
function DraftCard({draft:d,refresh}:{draft:ClientDraft;refresh:()=>Promise<void>}){
 const router=useRouter(),[checked,setChecked]=useState(false),[reason,setReason]=useState(''),[unsent,setUnsent]=useState(false),[notice,setNotice]=useState(''),[pending,start]=useTransition();
 function run(action:()=>Promise<{ok:boolean;message:string}>){start(async()=>{try{const r=await action();setNotice(r.message);if(r.ok){await refresh();router.refresh();}}catch{setNotice('Could not confirm the change. Refresh before retrying.');}});}
 return <details className="ember-person"><summary><strong>{d.source.clientName}</strong> · {d.invoice_number??'Draft'} · {money(d.total_cents)} · {d.status}<small>{d.period_start} – {d.period_end}</small></summary><p>Issue {d.issue_date} · Due {d.due_date}</p><p>Subtotal {money(d.subtotal_cents)} · GST {money(d.gst_cents)} · <strong>Total {money(d.total_cents)}</strong></p><p>Billing email: {d.source.clientEmail||'Not recorded'}</p><div style={{overflow:'auto',maxHeight:'50vh'}}><table className="office-draft-table"><thead><tr>{['Work date','Contractor / site','Actual h','Billable h','Rate ex GST','Amount ex GST'].map(label=><th key={label}>{label}</th>)}</tr></thead><tbody>{d.source.rows.map(r=><tr key={r.entryId}><td>{r.workDate}</td><td>{r.fullName}<small>{r.siteName}</small>{r.clientHours!==r.actualHours&&<small>{r.agreementNote}</small>}</td><td>{r.actualHours}</td><td>{r.clientHours}</td><td>{r.rateCents===null?'—':money(r.rateCents)}</td><td>{money(r.amountCents)}</td></tr>)}</tbody></table></div><div className="ember-chips"><a className="ember-link" href={`/api/office/client-drafts/${d.id}/pdf`} target="_blank" rel="noopener noreferrer">Download {d.status==='draft'?'draft ':''}invoice PDF</a><a className="ember-link" href={`/api/office/client-drafts/${d.id}/pdf?summary=1`} target="_blank" rel="noopener noreferrer">Download work summary · no amounts</a></div>
 {d.status==='draft'&&<><label><input type="checkbox" checked={checked} onChange={e=>setChecked(e.target.checked)} disabled={pending}/> I have checked the client, period, billable hours, rates and GST.</label><button className="ember-primary" disabled={pending||!checked} onClick={()=>run(()=>approveClientDraft(d.id,d.source_digest))}>Approve invoice</button></>}{d.status==='approved'&&<><p>Approved. These work records are locked against duplicate invoicing.</p><InvoiceEmail draft={d}/></>}{d.status!=='cancelled'&&<details><summary>Cancel / correct this invoice</summary><label>Reason<input value={reason} maxLength={1000} disabled={pending} onChange={e=>setReason(e.target.value)}/></label>{d.status==='approved'&&<label><input type="checkbox" checked={unsent} disabled={pending} onChange={e=>setUnsent(e.target.checked)}/> I confirm this invoice has never been sent to the client.</label>}<button disabled={pending||reason.trim().length<3||(d.status==='approved'&&!unsent)} onClick={()=>run(()=>cancelClientDraft(d.id,reason,unsent))}>Cancel and preserve history</button><p className="ember-footnote">For an invoice already sent, review the client’s correction request before issuing a replacement or credit. This control is for drafts and unsent invoices only.</p></details>}{d.cancel_reason&&<p>Cancellation: {d.cancel_reason}</p>}{notice&&<p role="status">{notice}</p>}</details>;
}
