"use client";
import { useState } from "react";
import { Archive,Building2,Download,DollarSign,MapPin,Plus,RotateCcw,ShieldCheck,UserPlus } from "lucide-react";
import {createOperationsClientAction,createOperationsLocationAction,inviteOperationsAdminAction,setOperationsLocationStatusAction,type OperationsActionResult} from "@/app/actions/operations";
import {isOperationsProjectActive} from "@/lib/operations/lifecycle";
import type {OperationsWorkspaceData} from "@/lib/operations/types";
export type CompanyManagementData=Pick<OperationsWorkspaceData,"clients"|"projects"|"clientInvoices"|"isFinanceAdmin">;
export function LocationsPanel({ data, isPending, runAction }: { data: CompanyManagementData; isPending: boolean; runAction: (action: () => Promise<OperationsActionResult>) => void }) {
  const [clientId, setClientId] = useState(data.clients[0]?.id ?? "");
  const [name, setName] = useState("");
  const [address, setAddress] = useState("");
  const activeProjects = data.projects.filter(isOperationsProjectActive);
  const completedProjects = data.projects.filter((project) => !isOperationsProjectActive(project));
  function submit() {
    runAction(async () => {
      const result = await createOperationsLocationAction({ clientId, name, address });
      if (result.ok) { setName(""); setAddress(""); }
      return result;
    });
  }
  function setLocationStatus(locationId: string, status: "active" | "completed") {
    runAction(() => setOperationsLocationStatusAction({ locationId, status }));
  }
  return <div className="grid gap-4 lg:grid-cols-[minmax(0,0.8fr)_minmax(0,1.2fr)]">
    <section className="dashboard-card">
      <div className="dashboard-card-header"><div className="dashboard-icon"><Plus className="size-5" /></div><div><h2 className="dashboard-card-title">Add a location</h2><p className="dashboard-muted">All operations users can add a new work location under an existing client.</p></div></div>
      <div className="grid gap-4"><Field label="Client"><select value={clientId} onChange={(event) => setClientId(event.target.value)}><option value="">Select client</option>{data.clients.map((client) => <option key={client.id} value={client.id}>{client.name}</option>)}</select></Field><Field label="Location / project name"><input value={name} onChange={(event) => setName(event.target.value)} placeholder="Example: Tonkin Highway package" /></Field><Field label="Site address"><input value={address} onChange={(event) => setAddress(event.target.value)} placeholder="Street, suburb, WA" /></Field><button className="dashboard-button dashboard-button-primary" disabled={isPending || !clientId || !name.trim() || !address.trim()} onClick={submit} type="button">{isPending ? "Adding…" : "Add location"}</button></div>
    </section>
    <section className="dashboard-card"><div className="dashboard-card-header"><div className="dashboard-icon"><MapPin className="size-5" /></div><div><h2 className="dashboard-card-title">Current locations</h2><p className="dashboard-muted">Only active locations are available for new daily records.</p></div></div><div className="grid gap-3 sm:grid-cols-2">{activeProjects.map((project) => { const client = data.clients.find((item) => item.id === project.clientId); return <article className="rounded-xl border border-gray-200 bg-gray-50 p-4" key={project.id}><p className="font-black text-blue-950">{project.name}</p><p className="mt-1 text-sm font-bold text-orange-600">{client?.name}</p><p className="mt-2 text-sm text-gray-600">{project.location}</p><button className="dashboard-button dashboard-button-outline mt-4 inline-flex items-center justify-center gap-2" disabled={isPending} onClick={() => setLocationStatus(project.id, "completed")} type="button"><Archive className="size-4" /> Mark completed</button></article>; })}</div>{activeProjects.length === 0 ? <EmptyState text="No active locations are available." /> : null}{completedProjects.length > 0 ? <div className="mt-6 border-t border-gray-200 pt-5"><h3 className="font-black text-blue-950">Completed locations</h3><p className="mt-1 text-sm text-gray-500">History remains available. Reactivate a location if work resumes.</p><div className="mt-3 grid gap-3 sm:grid-cols-2">{completedProjects.map((project) => { const client = data.clients.find((item) => item.id === project.clientId); return <article className="rounded-xl border border-gray-200 bg-gray-50 p-4" key={project.id}><p className="font-black text-blue-950">{project.name}</p><p className="mt-1 text-sm font-bold text-gray-600">{client?.name}</p><p className="mt-2 text-sm text-gray-600">{project.location}</p><button className="dashboard-button dashboard-button-outline mt-4 inline-flex items-center justify-center gap-2" disabled={isPending} onClick={() => setLocationStatus(project.id, "active")} type="button"><RotateCcw className="size-4" /> Reactivate</button></article>; })}</div></div> : null}</section>
  </div>;
}

export function ClientsAndAccessPanel({ data, isPending, runAction }: { data: CompanyManagementData; isPending: boolean; runAction: (action: () => Promise<OperationsActionResult>) => void }) {
  const [name, setName] = useState(""); const [abn, setAbn] = useState(""); const [email, setEmail] = useState(""); const [terms, setTerms] = useState("14"); const [inviteEmail, setInviteEmail] = useState("");
  function createClient() { runAction(async () => { const result = await createOperationsClientAction({ name, abn, billingEmail: email, paymentTermsDays: Number(terms) }); if (result.ok) { setName(""); setAbn(""); setEmail(""); setTerms("14"); } return result; }); }
  function inviteAdmin() { runAction(async () => { const result = await inviteOperationsAdminAction(inviteEmail); if (result.ok) setInviteEmail(""); return result; }); }
  return <div className="grid gap-4 lg:grid-cols-2"><section className="dashboard-card"><div className="dashboard-card-header"><div className="dashboard-icon"><Building2 className="size-5" /></div><div><h2 className="dashboard-card-title">Create client</h2><p className="dashboard-muted">Client setup is restricted to Bulgaa and Zaya.</p></div></div><div className="grid gap-4"><Field label="Client name"><input value={name} onChange={(event) => setName(event.target.value)} /></Field><Field label="ABN (optional)"><input value={abn} onChange={(event) => setAbn(event.target.value)} /></Field><Field label="Billing email"><input value={email} onChange={(event) => setEmail(event.target.value)} type="email" /></Field><Field label="Payment terms (days)"><input min="0" max="90" value={terms} onChange={(event) => setTerms(event.target.value)} type="number" /></Field><button className="dashboard-button dashboard-button-primary" disabled={isPending || name.trim().length < 2} onClick={createClient} type="button">Create client</button></div><div className="mt-5 grid gap-2">{data.clients.map((client) => <div className="rounded-lg bg-gray-100 px-3 py-2 text-sm font-bold" key={client.id}>{client.name}</div>)}</div></section>
    <section className="dashboard-card"><div className="dashboard-card-header"><div className="dashboard-icon"><UserPlus className="size-5" /></div><div><h2 className="dashboard-card-title">Invite operations admin</h2><p className="dashboard-muted">This role can manage locations and records, but receives no finance access.</p></div></div><div className="grid gap-4"><Field label="Email address"><input value={inviteEmail} onChange={(event) => setInviteEmail(event.target.value)} type="email" /></Field><button className="dashboard-button dashboard-button-primary" disabled={isPending || !inviteEmail.includes("@")} onClick={inviteAdmin} type="button">{isPending ? "Sending…" : "Send restricted invite"}</button></div><div className="mt-5 rounded-xl border border-emerald-200 bg-emerald-50 p-4"><p className="inline-flex items-center gap-2 font-black text-emerald-900"><ShieldCheck className="size-5" /> Access boundary</p><ul className="mt-3 grid gap-2 text-sm text-emerald-950"><li>✓ May add and complete locations under existing clients</li><li>✓ May record and review contractor hours</li><li>× Cannot create clients or contractors</li><li>× Cannot view rates, GST, invoices or payments</li></ul></div></section></div>;
}


export function ClientInvoiceHistory({data}:{data:CompanyManagementData}) {return (    <section className="dashboard-card"><div className="dashboard-card-header"><div className="dashboard-icon"><DollarSign className="size-5" /></div><div><h2 className="dashboard-card-title">Client invoices</h2><p className="dashboard-muted">Existing invoices · latest 100. Invoice and production summary are separate files.</p></div></div><div className="grid gap-3">{data.clientInvoices.map((invoice) => { const client = data.clients.find((item) => item.id === invoice.clientId); return <article className="rounded-xl border border-gray-200 p-4" key={invoice.id}><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><p className="font-black text-blue-950">{invoice.invoiceNumber}</p><p className="mt-1 text-sm text-gray-600">{client?.name} · {formatDate(invoice.periodStart)}–{formatDate(invoice.periodEnd)}</p><span className="mt-2 inline-block rounded-full bg-blue-100 px-2.5 py-1 text-xs font-bold text-blue-800">{invoice.status}</span></div><div className="sm:text-right"><p className="text-xl font-black text-blue-950">{formatMoney(invoice.totalAmount)}</p><p className="text-xs text-gray-500">GST {formatMoney(invoice.gstAmount)}</p><div className="mt-3 flex flex-wrap gap-2 sm:justify-end"><a className="inline-flex min-h-10 items-center gap-2 rounded-lg border border-orange-300 bg-orange-50 px-3 py-2 text-sm font-bold text-orange-800 hover:bg-orange-100" href={`/api/operations/client-invoices/${invoice.id}/pdf`}><Download className="size-4" /> Invoice PDF</a><a className="inline-flex min-h-10 items-center gap-2 rounded-lg border border-gray-300 px-3 py-2 text-sm font-bold text-blue-950 hover:bg-gray-50" href={`/api/operations/client-invoices/${invoice.id}/production-summary`}><Download className="size-4" /> Production summary PDF</a></div></div></div></article>; })}</div>{data.clientInvoices.length === 0 ? <EmptyState text="No client invoices have been created yet." /> : null}</section>);}
function Field({ children, label }: { children: React.ReactNode; label: string }) { return <label className="dashboard-label">{label}{children}</label>; }
function EmptyState({ text }: { text: string }) { return <div className="p-6 text-center text-sm text-gray-500">{text}</div>; }
function formatMoney(value: number) { return new Intl.NumberFormat("en-AU", { style: "currency", currency: "AUD" }).format(value); }
function formatDate(value: string) { const [year, month, day] = value.split("-"); return `${day}/${month}/${year}`; }
