'use client';
import {useRef,useState} from 'react';
import {useRouter} from 'next/navigation';
import {saveContractorName} from '@/app/actions/contractor-names';
import type {OfficeData} from '@/lib/office/foundation';
export function ContractorNames({people}:{people:OfficeData['contractors']}){
 const router=useRouter(),[search,setSearch]=useState(''),[worker,setWorker]=useState(''),[short,setShort]=useState(''),[aliases,setAliases]=useState(''),[notice,setNotice]=useState(''),[pending,setPending]=useState(false);const event=useRef('');const person=people.find(p=>p.id===worker);
 const edit=(fn:()=>void)=>{event.current='';fn();};
 return <section className="ember-panel"><h2>Short names</h2><p className="muted">Bobby recognises these names in every chat. Client work summaries use the short name only.</p><details><summary>Manage short names · {people.filter(p=>!p.shortName).length} to add</summary><input aria-label="Find contractor short name" placeholder="Full name or nickname…" value={search} onChange={e=>setSearch(e.target.value)}/><div className="ember-chips office-name-options">{people.filter(p=>[p.fullName,p.shortName,...(p.aliases??[])].join(' ').toLowerCase().includes(search.toLowerCase())).map(p=><button key={p.id} disabled={pending} onClick={()=>edit(()=>{setWorker(p.id);setShort(p.shortName??'');setAliases((p.aliases??[]).join(', '));})}>{p.shortName||'Name needed'} · {p.fullName}</button>)}</div></details>{person&&<form onSubmit={async e=>{e.preventDefault();if(pending)return;setPending(true);if(!event.current)event.current=crypto.randomUUID();try{const r=await saveContractorName(event.current,{workerId:person.id,fullName:person.fullName,shortName:short,aliases:aliases.split(',').map(v=>v.trim()).filter(Boolean),expectedVersion:person.nameVersion??0});setNotice(r.message);if(r.ok){setWorker('');event.current='';router.refresh();}}catch{setNotice('Save could not be confirmed. Retry with the same details.');}finally{setPending(false);}}}><h3>{person.fullName}</h3><label>Short name on client summaries<input required maxLength={80} value={short} disabled={pending} onChange={e=>edit(()=>setShort(e.target.value))}/></label><label>Other names Bobby should recognise (comma-separated)<input value={aliases} disabled={pending} onChange={e=>edit(()=>setAliases(e.target.value))}/></label><button className="ember-primary" disabled={pending}>{pending?'Saving…':'Save short name'}</button></form>}{notice&&<p role="status">{notice}</p>}</section>;
}
