'use client';
import {useState} from 'react';
import {directRequest,DIRECT_LABELS,type DirectRequest,type DirectResult} from '@/lib/office/direct';
import {DocumentUpload,DocumentCapture} from './document-upload';
export function DirectTools({pending,run}:{pending:boolean;run:(r:DirectRequest)=>void}){
 const [kind,setKind]=useState<DirectRequest['kind']>('mail'),[query,setQuery]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState('');
 return <details className="office-direct-tools"><summary>Office tools · works with Mac off</summary><form onSubmit={e=>{e.preventDefault();run(directRequest.parse({kind,query,from,to}));}}><p className="ember-footnote">Live email, saved records and exact calculations. AI reasoning can continue on your Mac.</p><label>Find<select value={kind} disabled={pending} onChange={e=>setKind(e.target.value as DirectRequest['kind'])}>{(['mail','invoices','contacts','documents','work','company','plans','missing_hours'] as const).map(k=><option key={k} value={k}>{DIRECT_LABELS[k]}</option>)}</select></label><label>Name or search<input disabled={pending} placeholder={kind==='mail'?'Name, subject, has:attachment…':'Name, short name, number…'} value={query} maxLength={500} onChange={e=>setQuery(e.target.value)}/></label>{['mail','invoices','work','plans'].includes(kind)&&<div className="office-direct-dates"><label>From<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>To<input type="date" min={from} value={to} onChange={e=>setTo(e.target.value)}/></label></div>}<button className="ember-primary" disabled={pending||!!from&&!!to&&from>to} type="submit">{pending?'Working…':'Find now'}</button></form></details>;
}
export function DirectResultView({result,pending,run}:{result:DirectResult;pending:boolean;run:(r:DirectRequest)=>void}){
 const [notice,setNotice]=useState(''),[file,setFile]=useState<{label:string;url:string}|null>(null),[capture,setCapture]=useState<{title:string;url:string}|null>(null);
 const body=result.bodyFormat==='html'?result.body?.replace(/<style\b[^>]*>[\s\S]*?<\/style>|<script\b[^>]*>[\s\S]*?<\/script>/gi,'').replace(/<[^>]*>/g,' ').replace(/&nbsp;/g,' '):result.body;
 return <div className="office-direct-result"><p className="ember-footnote">Direct office result · {new Date(result.checkedAt).toLocaleString('en-AU',{timeZone:'Australia/Perth'})}</p>{result.status&&<strong className={result.status==='match'?'office-match':'error'}>{result.status==='match'?'Calculation matched':result.status==='difference'?'Amount differs':'Needs review'}</strong>}{result.issues?.map((issue,i)=><p className="error" key={i}>{issue}</p>)}{body&&<div className="office-mail-body">{body}</div>}{result.rows.map(row=><article className="office-direct-row" key={row.id}><strong>{row.title}</strong><p style={{whiteSpace:'pre-wrap'}}>{row.detail}</p><div className="ember-chips">{row.copy&&<button onClick={()=>void navigator.clipboard.writeText(row.copy!).then(()=>setNotice('Contact details copied.')).catch(()=>setNotice('Copy unavailable. Select the contact details above.'))}>Copy contact</button>}{row.next&&<button className="ember-primary" disabled={pending} onClick={()=>run(row.next!)}>{row.next.kind==='message'?'Read email':row.next.kind==='check_invoice'?'Compare with records':'Show daily work'}</button>}{row.source&&<a href={row.source} target="_blank" rel="noopener noreferrer">Original source ↗</a>}</div>{row.files?.map(f=><div className="ember-chips" key={f.id}><button onClick={()=>setFile(f)}>{f.label}</button><a href={f.url+'&download=1'}>Download</a>{result.request.kind==='message'&&<button onClick={()=>setCapture({title:f.label,url:'https://www.stillpartners.net'+f.url})}>Save to Documents</button>}</div>)}{result.request.kind==='documents'&&<DocumentUpload documentId={row.id} onSaved={()=>run({...result.request,cursor:''})}/>}</article>)}{!result.rows.length&&<p>No matching records found in this source.</p>}<p className="ember-footnote">{result.coverage}</p>{result.nextCursor&&<button disabled={pending} onClick={()=>run({...result.request,cursor:result.nextCursor!})}>Next page</button>}{notice&&<p role="status">{notice}</p>}{capture&&<DocumentCapture initial={capture} onClose={()=>setCapture(null)}/>} {file&&<div className="office-file-preview" role="dialog" aria-modal="true" aria-label={file.label}><div className="ember-chips"><strong>{file.label}</strong><button onClick={()=>setFile(null)}>Close</button><a href={file.url} target="_blank" rel="noopener noreferrer">Open full screen ↗</a></div><iframe title={file.label} src={file.url}/><p className="ember-footnote">If the phone cannot preview this file, use Open full screen or Download.</p></div>}</div>;
}
