'use client';
import {DocumentUpload} from './document-upload';
import {useEffect,useRef,useState} from 'react';
import {listOfficeDocuments,saveOfficeDocument,officeDocumentHistory} from '@/app/actions/documents';
import {documentDraft,documentExpiry,safeDocumentUrl,type DocumentInput,type OfficeDocument} from '@/lib/office/documents';
import type {OfficeData} from '@/lib/office/foundation';
export function DocumentCatalog({data,today}:{data:OfficeData;today:string}){
 const [rows,setRows]=useState<OfficeDocument[]>([]),[draft,setDraft]=useState<DocumentInput|null>(null),[search,setSearch]=useState(''),[all,setAll]=useState(false),[notice,setNotice]=useState(''),[pending,setPending]=useState(false),[history,setHistory]=useState<{created_at:string;after_data:OfficeDocument}[]|null>(null);const event=useRef(''),editor=useRef<HTMLFormElement>(null);
 async function refresh(){try{setRows(await listOfficeDocuments());}catch{setNotice('Could not load documents. Try Refresh.');}}
 useEffect(()=>{void refresh();},[]);
 const editingId=draft?.id;
 useEffect(()=>{if(editingId){editor.current?.scrollIntoView({block:'start',behavior:'smooth'});editor.current?.querySelector('input')?.focus();}},[editingId]);
 function patch(v:Partial<DocumentInput>){event.current='';setDraft(d=>d?{...d,...v}:d);}
 const owner=(d:OfficeDocument)=>d.entity_type==='company'?'Still Partners':(d.entity_type==='contractor'?data.contractors.find(p=>p.id===d.entity_id)?.fullName:data.clients.find(p=>p.id===d.entity_id)?.name)??'Record unavailable';
 return <section className="ember-panel"><div className="ember-section-heading"><h2>Documents</h2><button className="ember-primary" disabled={pending} onClick={()=>{event.current='';setDraft(documentDraft());setHistory(null);}}>Add document</button></div><p className="muted">Find company, contractor and client documents by name, type or source. Keep Gmail originals linked, or add a private copy to open while your Mac is off.</p><input aria-label="Search documents" placeholder="Name, insurance, licence…" value={search} onChange={e=>setSearch(e.target.value)}/><div className="ember-chips"><button onClick={()=>void refresh()}>Refresh</button><button aria-pressed={all} onClick={()=>setAll(!all)}>{all?'Including archive':'Active documents'}</button><a href="/office/mail">Find in work Gmail →</a></div>
 {notice&&<p role="status" className="ember-notice">{notice}</p>}
 {rows.filter(d=>(all||d.status==='active')&&[d.title,owner(d),d.category,d.source_note,d.notes].join(' ').toLowerCase().includes(search.trim().toLowerCase())).map(d=>{const expiry=documentExpiry(d,today),url=safeDocumentUrl(d.source_url);return <article className="ember-person" key={d.id}><strong>{d.title}</strong><p>{owner(d)} · {d.category.replaceAll('_',' ')} · {d.status}</p>{d.expires_on&&<p className={['expired','due'].includes(expiry.status)?'error':'muted'}>Expiry {d.expires_on} · {expiry.status==='unverified'?'Date needs confirmation':expiry.status==='expired'?'Expired':expiry.status==='due'?`${expiry.days} days remaining`:'Confirmed date'}</p>}<p>{d.source_note}</p>{url&&<a className="ember-link" href={url} target="_blank" rel="noopener noreferrer">Open original source ↗</a>}<p>{d.notes}</p>{d.files?.map(f=><p key={f.id}><a className="ember-link" href={`/api/office/documents/file?id=${f.id}`} target="_blank" rel="noopener noreferrer">{f.filename} ↗</a> · {Math.ceil(f.bytes/1024)} KB</p>)}{d.status==='active'&&<DocumentUpload documentId={d.id} onSaved={()=>void refresh()}/>}<div className="ember-chips"><button disabled={pending} onClick={()=>{event.current='';setDraft(documentDraft(d));setHistory(null);}}>Edit / renew</button><button onClick={()=>void officeDocumentHistory(d.id).then(r=>{setHistory(r);setDraft(null);}).catch(()=>setNotice('History unavailable.'))}>Version history</button></div></article>;})}
 {!rows.length&&<p className="ember-empty">Add a Gmail source link or document reference, then attach a private copy if needed.</p>}
 {history&&<details open><summary>Document version history</summary>{history.map((h,i)=><p key={i}>v{h.after_data.version} · {h.created_at} · {h.after_data.title} · {h.after_data.status} · Expiry {h.after_data.expires_on??'not recorded'}</p>)}</details>}
 {draft&&<form ref={editor} className="ember-panel" onSubmit={async e=>{e.preventDefault();if(pending)return;setPending(true);if(!event.current)event.current=crypto.randomUUID();try{const r=await saveOfficeDocument(event.current,draft);setNotice(r.message);if(r.ok){setDraft(null);event.current='';await refresh();}}catch{setNotice('Save could not be confirmed. Retry with the same details.');}finally{setPending(false);}}}><h3>{draft.expectedVersion?'Edit document':'New document'}</h3><fieldset disabled={pending} className="office-document-fields"><label>Title<input required maxLength={160} value={draft.title} onChange={e=>patch({title:e.target.value})}/></label><label>Belongs to<select value={draft.entityType} onChange={e=>patch({entityType:e.target.value as DocumentInput['entityType'],entityId:''})}><option value="company">Company</option><option value="contractor">Contractor</option><option value="client">Client</option></select></label>{draft.entityType!=='company'&&<label>Name<select required value={draft.entityId} onChange={e=>patch({entityId:e.target.value})}><option value="">Select…</option>{(draft.entityType==='contractor'?data.contractors.map(p=>({id:p.id,name:p.fullName})):data.clients).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>}<label>Type<select value={draft.category} onChange={e=>patch({category:e.target.value as DocumentInput['category']})}>{['insurance','licence','white_card','cv','agreement','other'].map(c=><option key={c} value={c}>{c.replaceAll('_',' ')}</option>)}</select></label><label>Source link<input type="url" placeholder="https://mail.google.com/…" value={draft.sourceUrl} onChange={e=>patch({sourceUrl:e.target.value})}/></label><label>Source location / filename<input maxLength={1000} value={draft.sourceNote} onChange={e=>patch({sourceNote:e.target.value})}/></label><label>Expiry date (optional)<input type="date" value={draft.expiresOn} onChange={e=>patch({expiresOn:e.target.value,expiryConfirmed:false})}/></label>{draft.expiresOn&&<label><input type="checkbox" checked={draft.expiryConfirmed} onChange={e=>patch({expiryConfirmed:e.target.checked})}/> I checked this expiry date on the document</label>}<label>Notes<textarea maxLength={4000} value={draft.notes} onChange={e=>patch({notes:e.target.value})}/></label><label>Status<select value={draft.status} onChange={e=>patch({status:e.target.value as DocumentInput['status']})}><option value="active">Active</option><option value="archived">Archived</option></select></label><div className="ember-chips"><button className="ember-primary" type="submit">{pending?'Saving…':'Save document'}</button><button type="button" onClick={()=>setDraft(null)}>Cancel</button></div></fieldset></form>}
 </section>;
}
