'use client';
import {useEffect,useRef,useState} from 'react';
import {saveOfficeDocument,documentOwners} from '@/app/actions/documents';
import {documentDraft,type DocumentInput} from '@/lib/office/documents';
export function DocumentUpload({documentId,onSaved}:{documentId:string;onSaved:()=>void}){
 const [pending,setPending]=useState(false),[notice,setNotice]=useState('');const id=useRef(''),input=useRef<HTMLInputElement>(null);
 async function upload(file:File){if(pending)return;setPending(true);setNotice('Uploading private copy…');if(!id.current)id.current=crypto.randomUUID();const form=new FormData();form.set('id',id.current);form.set('documentId',documentId);form.set('file',file);
  try{const response=await fetch('/api/office/documents/file',{method:'POST',body:form}),r=await response.json();if(!response.ok||!r.ok)throw new Error(r.error||'Upload not confirmed');setNotice(r.message);id.current='';if(input.current)input.current.value='';onSaved();}catch(e){setNotice(e instanceof Error?e.message:'Upload not confirmed. Retry with the same file.');}finally{setPending(false);}}
 return <div className="office-document-upload"><label>Add private file<input ref={input} disabled={pending} type="file" accept=".pdf,.png,.jpg,.jpeg,.webp,.txt" onChange={()=>{id.current='';setNotice('');}}/></label><button disabled={pending} onClick={()=>{const f=input.current?.files?.[0];if(f)void upload(f);else setNotice('Choose a file first.');}}>{pending?'Uploading…':'Save private copy'}</button><small>Up to 3 MB per file. Larger documents can stay in Gmail.</small>{notice&&<p role="status">{notice}</p>}</div>;
}
export function DocumentCapture({initial,onClose}:{initial:{title:string;url:string};onClose:()=>void}){
 const [draft,setDraft]=useState<DocumentInput>(()=>({...documentDraft(),title:initial.title.slice(0,160),sourceUrl:initial.url,sourceNote:'Original Gmail attachment'})),[owners,setOwners]=useState<Awaited<ReturnType<typeof documentOwners>>|null>(null),[pending,setPending]=useState(false),[notice,setNotice]=useState('');const event=useRef(crypto.randomUUID());
 useEffect(()=>{void documentOwners().then(setOwners).catch(()=>setNotice('Owner list could not load. Retry later.'));},[]);
 function patch(v:Partial<DocumentInput>){event.current=crypto.randomUUID();setDraft(d=>({...d,...v}));}
 return <form className="ember-panel" onSubmit={async e=>{e.preventDefault();setPending(true);try{const r=await saveOfficeDocument(event.current,draft);setNotice(r.message);if(r.ok)onClose();}catch{setNotice('Save not confirmed. Retry is safe.');}finally{setPending(false);}}}><h3>Save Gmail document</h3><label>Title<input required value={draft.title} onChange={e=>patch({title:e.target.value})}/></label><label>Belongs to<select value={draft.entityType} onChange={e=>patch({entityType:e.target.value as DocumentInput['entityType'],entityId:''})}><option value="company">Company</option><option value="contractor">Contractor</option><option value="client">Client</option></select></label>{draft.entityType!=='company'&&<label>Name<select required value={draft.entityId} onChange={e=>patch({entityId:e.target.value})}><option value="">Select…</option>{(draft.entityType==='contractor'?owners?.contractors:owners?.clients)?.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>}<label>Type<select value={draft.category} onChange={e=>patch({category:e.target.value as DocumentInput['category']})}>{['insurance','licence','white_card','cv','agreement','other'].map(v=><option key={v} value={v}>{v.replaceAll('_',' ')}</option>)}</select></label><div className="ember-chips"><button className="ember-primary" disabled={pending} type="submit">{pending?'Saving…':'Save document'}</button><button type="button" disabled={pending} onClick={onClose}>Cancel</button></div>{notice&&<p role="status">{notice}</p>}</form>;
}
