"use client";
import { useEffect, useState, useTransition, type CSSProperties } from "react";
import type {InvoiceEvent} from "@/lib/office/invoice-events";
import {InvoiceRegister} from "./invoice-register";
import type {InvoiceSnapshot} from "@/lib/office/invoice-snapshot";
import {logout} from "@/app/actions/auth";
import {LocationsPanel,ClientsAndAccessPanel,ClientInvoiceHistory,type CompanyManagementData} from "./company-management";
import type {OperationsActionResult} from "@/app/actions/operations";
import Image from "next/image";
import { useRouter } from "next/navigation";
import { CalendarDays, Sparkles, CheckCheck, Building2, Plus, ArrowUpRight, Users, Clock3 } from "lucide-react";
import { saveOfficeWork, type OfficeResult } from "@/app/actions/office";
import { directory, type OfficeData, type OfficeEntry } from "@/lib/office/foundation";
import { Contacts, History, Rates } from "./office-workspace";
import { ContactImportReview } from "./contact-import-review";
import "./ember.css";

type Draft={actual:string;pay:string;bill:string;note:string;adjust:boolean;dirty:boolean;saved?:boolean;error?:string};
const initial=(e?:OfficeEntry):Draft=>({actual:e?String(e.actualHours):"",pay:e?String(e.contractorHours??e.actualHours):"",bill:e?String(e.clientHours??e.actualHours):"",note:e?.agreementNote??"",adjust:!!e&&(e.contractorHours!==e.actualHours||e.clientHours!==e.actualHours),dirty:false});
const colors=["#b4a0e8","#83b9e1","#92cdb8","#e8b783"];
const clientColor=(id:string)=>colors[Array.from(id).reduce((n,c)=>n+c.charCodeAt(0),0)%colors.length];
export function EmberWorkspace({data,management,snapshot,invoiceEvents,today,initialTab="daily"}:{data:OfficeData;snapshot:InvoiceSnapshot|null;invoiceEvents:InvoiceEvent[];management:CompanyManagementData;today:string;initialTab?:"daily"|"history"}) {
 const router=useRouter();const [tab,setTab]=useState(initialTab==="history"?"company":"today");const [section,setSection]=useState(initialTab==="history"||!data.finance?"history":"contacts");const [pending,start]=useTransition();const [notice,setNotice]=useState<OfficeResult|null>(null);
 const runManagement=(action:()=>Promise<OperationsActionResult>)=>run(async()=>{const r=await action();return {ok:r.ok,message:r.message??r.error??(r.ok?"Saved.":"Could not save.")};});
 const count=(data.contactImports??[]).filter(i=>i.status==="pending").length;
 const run=(action:()=>Promise<OfficeResult>)=>start(async()=>{try{const r=await action();setNotice(r);if(r.ok)router.refresh();}catch{setNotice({ok:false,message:"Could not save. Please try again."});}});
 return <main className="ember"><div className="ember-shell"><header className="ember-top"><a href="/office" className="ember-brand"><Image src="/assets/logo/logo-icon-light.svg" alt="Still Partners" width="38" height="38"/><span>STILL PARTNERS<small>YOUR COMPANY OFFICE</small></span></a><form action={logout}><button type="submit" className="ember-text-button">Sign out</button></form></header>
 <div className="ember-content"><div className="ember-heading"><p className="eyebrow">STILL PARTNERS / OFFICE</p><h1>{tab==="today"?"Your day, organised.":tab==="assistant"?"Meet your assistant.":tab==="approvals"?"Ready for your review.":"Your company."}</h1><p className="muted">{new Intl.DateTimeFormat("en-AU",{weekday:"long",day:"numeric",month:"long",year:"numeric",timeZone:"Australia/Perth"}).format(new Date(today+"T12:00:00+08:00"))}</p></div>
 {notice&&<p role="status" className={notice.ok?"ember-notice":"ember-notice error"}>{notice.message}</p>}
 <div hidden={tab!=="today"}><section className="ember-agent"><div className="orb"/><div><p className="eyebrow">OFFICE OVERVIEW</p><p>{data.entries.filter(e=>e.workDate===today).length} work records today{data.finance?` · ${count} contacts to review`:""}</p><button onClick={()=>{if(!data.finance)setSection("history");setTab(data.finance?"approvals":"company");}}> {data.finance?"Review contacts":"View work history"} <ArrowUpRight size={15}/></button></div></section><SiteDay data={data} today={today} openSites={()=>{setSection("sites");setTab("company");}}/></div>
 {tab==="assistant"&&<section className="ember-panel assistant-panel"><div className="orb large"/><h2>JARVIS</h2><p>Your office, one conversation away.</p><p className="muted">Text and voice commands are not connected yet. Your work records and company tools below are available now.</p><div className="ember-chips"><button onClick={()=>setTab("today")}>Record today’s work</button><button onClick={()=>{setSection(data.finance?"contacts":"history");setTab("company");}}>Find a contractor</button><button onClick={()=>setTab("approvals")}>Open reviews</button></div></section>}
 {tab==="approvals"&&<><section className="ember-panel"><p className="eyebrow">REVIEW QUEUE</p><h2>{data.finance?`${count} contact sources to review`:"Finance access required"}</h2><p className="muted">Review supplier identity before adding a contact. Contractor invoice and payment review from the Mac assistant is not connected to this page yet.</p><button className="ember-link" onClick={()=>{setSection("invoices");setTab("company");}}>Client invoice history <ArrowUpRight size={16}/></button></section>{data.finance&&<ContactImportReview items={data.contactImports??[]} people={data.contractors} pending={pending} run={run}/>}</>}
 {tab==="company"&&<><div className="ember-chips" aria-label="Company sections">{[...(data.finance?[["contacts","Contractors"],["rates","Agreed rates"],["clients","Clients & access"],["invoices","Client invoices"],["contractor-invoices","Contractor invoices"]]:[]),["sites","Clients & sites"],["history","Work history"]].map(([id,label])=><button aria-pressed={section===id} key={id} onClick={()=>setSection(id)}>{label}</button>)}</div>{section==="contractor-invoices"&&data.finance&&<InvoiceRegister snapshot={snapshot} events={invoiceEvents} today={today}/>} {section==="contacts"&&data.finance&&<Contacts data={data} pending={pending} run={run}/>} {section==="rates"&&data.finance&&<Rates data={data} today={today} pending={pending} run={run}/>} {section==="history"&&<History data={data}/>} {section==="sites"&&<LocationsPanel data={management} isPending={pending} runAction={runManagement}/>} {section==="clients"&&data.finance&&<ClientsAndAccessPanel data={management} isPending={pending} runAction={runManagement}/>} {section==="invoices"&&data.finance&&<><p className="ember-notice">Invoice history is available below. Creating invoices from the new agreed hours and rates is not connected yet.</p><ClientInvoiceHistory data={management}/></>}</>}
 </div><nav className="ember-nav" aria-label="Main navigation">{[["today","Today",CalendarDays],["assistant","Assistant",Sparkles],["approvals","Approvals",CheckCheck],["company","Company",Building2]].map(([id,label,Icon])=>{const Glyph=Icon as typeof CalendarDays;return <button key={String(id)} aria-current={tab===id?"page":undefined} onClick={()=>setTab(String(id))}><Glyph size={21}/><span>{String(label)}</span></button>;})}</nav></div></main>;
}
function SiteDay({data,today,openSites}:{data:OfficeData;today:string;openSites:()=>void}) {
 const router=useRouter();const [day,setDay]=useState(data.from===data.to?data.from:today);const [site,setSite]=useState("");const [drafts,setDrafts]=useState<Record<string,Draft>>({});const [picker,setPicker]=useState(false);const [search,setSearch]=useState("");const [all,setAll]=useState("");const [saving,setSaving]=useState(false);const [message,setMessage]=useState("");
 const key=(id:string)=>`${day}:${site}:${id}`;const entries=data.entries.filter(e=>e.workDate===day&&e.jobId===site);const entry=(id:string)=>entries.find(e=>e.workerId===id);const row=(id:string)=>drafts[key(id)]??initial(entry(id));
 const dirty=Object.values(drafts).some(d=>d.dirty);
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue="";}};window.addEventListener("beforeunload",warn);return()=>window.removeEventListener("beforeunload",warn);},[dirty]);
 const people=directory(data.contractors).filter(p=>entry(p.id)||drafts[key(p.id)]);
 const outside=day<data.from||day>data.to;const project=data.projects.find(p=>p.id===site);
 function patch(id:string,change:Partial<Draft>) {setDrafts(d=>({...d,[key(id)]:{...row(id),...change,dirty:true,saved:false,error:undefined}}));}
 function add(ids:string[]){setDrafts(d=>{const next={...d};ids.forEach(id=>{if(!next[key(id)]&&!entry(id))next[key(id)]=initial();});return next;});}
 function actual(id:string,value:string){const r=row(id);patch(id,{actual:value,pay:r.pay===r.actual?value:r.pay,bill:r.bill===r.actual?value:r.bill});}
 function previous(){const dates=data.entries.filter(e=>e.jobId===site&&e.workDate<day).map(e=>e.workDate).sort();const last=dates.at(-1);if(!last){setMessage("No previous team found in the loaded date range.");return;}add(data.entries.filter(e=>e.jobId===site&&e.workDate===last).map(e=>e.workerId).filter(id=>data.contractors.some(p=>p.id===id&&p.active)));setMessage("Previous team added. Enter today’s hours; earlier hours were not copied.");}
 async function save(){setSaving(true);setMessage("");let ok=0,failed=0;for(const p of people){const r=row(p.id);if(!r.dirty||entry(p.id)?.locked)continue;let error="";if(!r.actual||!/^\d+(\.\d{1,2})?$/.test(r.actual)||Number(r.actual)>24)error="Enter actual hours between 0 and 24 (up to 2 decimals).";if(data.finance&&(!r.pay||!r.bill||!/^\d+(\.\d{1,2})?$/.test(r.pay)||!/^\d+(\.\d{1,2})?$/.test(r.bill)||Number(r.pay)>24||Number(r.bill)>24))error="Enter valid payable and billable hours.";if(data.finance&&(Number(r.pay)!==Number(r.actual)||Number(r.bill)!==Number(r.actual))&&r.note.trim().length<3)error="Add the agreed reason for different hours.";
 if(!error){try{const result=await saveOfficeWork({workerId:p.id,jobId:site,workDate:day,actualHours:Number(r.actual),contractorHours:data.finance?Number(r.pay):null,clientHours:data.finance?Number(r.bill):null,agreementNote:data.finance?r.note:null,expectedUpdatedAt:entry(p.id)?.updatedAt??null});if(!result.ok)error=result.message;}catch{error="Save could not be confirmed. Reload the date before retrying.";}}
 const rowKey=key(p.id);setDrafts(d=>({...d,[rowKey]:{...r,dirty:!!error,saved:!error,error}}));if(error)failed++;else ok++;}
 setMessage(`${ok} saved${failed?` · ${failed} need attention. Saved rows will not be submitted again.`:". Work records updated."}`);setSaving(false);router.refresh();}
 return <section><div className="ember-section-heading"><h2>Today’s sites</h2><label className="ember-date"><CalendarDays size={16}/><input aria-label="Work date" type="date" value={day} max={today} disabled={saving} onChange={e=>{setDay(e.target.value);setMessage("");}}/></label></div><p className="muted">Choose a site, then add your team.</p><div className="ember-site-grid">{data.projects.filter(p=>p.active&&data.clients.some(c=>c.id===p.clientId&&c.active)).map(p=><button className={`ember-site ${site===p.id?"selected":""}`} disabled={saving} aria-pressed={site===p.id} key={p.id} style={{"--client":clientColor(p.clientId)} as CSSProperties} onClick={()=>{setSite(p.id);setPicker(false);setMessage("");}}><span className="client-label">{data.clients.find(c=>c.id===p.clientId)?.name}</span><strong>{p.name}</strong><small>{data.entries.filter(e=>e.jobId===p.id&&e.workDate===day).length} recorded <ArrowUpRight size={14}/></small></button>)}</div>
 {!data.projects.some(p=>p.active)&&<p className="ember-panel">No active sites are available. Add a site in <button className="ember-link" onClick={openSites}>Company → Clients & sites</button>.</p>}
 {outside?<p className="ember-notice">Load the selected date to edit its records. {dirty?"Save your entered hours before loading another range.":<a href={`/office?from=${day}&to=${day}`}>Load selected date</a>}</p>:site?<section className="ember-panel"><div className="ember-section-heading"><div><p className="eyebrow">{project?.name}</p><h2>Your team <span className="muted">{people.length}</span></h2></div><Users size={20}/></div><div className="ember-chips"><button disabled={saving} onClick={()=>setPicker(!picker)}><Plus size={15}/> Add contractors</button><button disabled={saving} onClick={previous}>Previous team</button></div>
 {picker&&<div className="ember-picker"><input aria-label="Search contractors" placeholder="Search full name…" value={search} onChange={e=>setSearch(e.target.value)}/>{directory(data.contractors,search).filter(p=>p.active&&!people.some(x=>x.id===p.id)).map(p=><button disabled={saving} key={p.id} onClick={()=>add([p.id])}><Plus size={15}/>{p.fullName}<small>{p.group==="occasional"?"Occasional":"Regular"}</small></button>)}</div>}
 {people.length>0&&<div className="ember-bulk"><Clock3 size={18}/><input aria-label="Hours to apply to all" type="number" min="0" max="24" step="0.01" placeholder="Hours" value={all} disabled={saving} onChange={e=>setAll(e.target.value)}/><button disabled={saving||all===""||Number(all)<0||Number(all)>24} onClick={()=>{people.filter(p=>!entry(p.id)?.locked&&!row(p.id).saved).forEach(p=>actual(p.id,all));}}>Apply to all</button></div>}
 {people.map(p=>{const r=row(p.id);const locked=!!entry(p.id)?.locked;const disabled=saving||locked||!!r.saved;return <article className="ember-person" key={p.id}><div className="ember-person-top"><div><strong>{p.fullName}</strong><small>{locked?"Locked / invoiced":r.saved?"Saved ✓":r.dirty?"Unsaved changes":entry(p.id)?"Recorded":"Hours not entered"}</small></div><label>Actual hours<input aria-label={`${p.fullName} actual hours`} type="number" min="0" max="24" step="0.01" inputMode="decimal" placeholder="—" value={r.actual} disabled={disabled} onChange={e=>actual(p.id,e.target.value)}/></label></div>{data.finance&&<button className="ember-text-button" disabled={disabled} onClick={()=>patch(p.id,{adjust:!r.adjust})}>{r.adjust?"Hide adjustment":"Adjustment"}</button>}{r.adjust&&data.finance&&<div className="ember-adjust"><label>Contractor hours<input type="number" min="0" max="24" step="0.01" value={r.pay} disabled={disabled} onChange={e=>patch(p.id,{pay:e.target.value})}/></label><label>Client hours<input type="number" min="0" max="24" step="0.01" value={r.bill} disabled={disabled} onChange={e=>patch(p.id,{bill:e.target.value})}/></label><label className="wide">Agreement / reason<input value={r.note} disabled={disabled} onChange={e=>patch(p.id,{note:e.target.value})}/></label></div>}{r.saved&&entry(p.id)&&<button className="ember-text-button" disabled={saving} onClick={()=>setDrafts(d=>({...d,[key(p.id)]:initial(entry(p.id))}))}>Edit saved hours</button>}{r.error&&<p className="error" role="alert">{r.error}</p>}{!entry(p.id)&&!r.saved&&<button className="ember-text-button" disabled={saving} onClick={()=>{if(r.dirty&&!window.confirm("Remove this unsaved row?"))return;setDrafts(d=>{const n={...d};delete n[key(p.id)];return n;});}}>Remove from team</button>}</article>;})}
 {!people.length&&<p className="ember-empty">Add the contractors who worked at this site.</p>}
 <button className="ember-primary" disabled={saving||!people.some(p=>row(p.id).dirty&&!entry(p.id)?.locked)} onClick={save}>{saving?"Saving work records…":"Save work records"}</button><p className="ember-footnote">Actual work, contractor payable hours and client billable hours remain separate.</p></section>:<p className="ember-empty">Select a site above to start.</p>}
 {message&&<p className="ember-notice" role="status">{message}</p>}{dirty&&<p className="ember-footnote">Unsaved entries are kept while switching tabs and sites. Save them before closing this page.</p>}
 </section>;
}
