"use client";
import {useSearchParams} from 'next/navigation';
import {PayrunSummary} from './payrun-summary';
import {upcomingPayday,payrunPeriod,invoiceInPayrun,isRegularPayday} from '@/lib/office/payrun';
import {invoicePeriod} from '@/lib/office/reconciliation';
import {paymentReadiness} from '@/lib/office/payment-readiness';
import {validDate} from '@/lib/office/foundation';
import {InvoiceReconciliation} from "./invoice-reconciliation";
import type {OfficeData} from "@/lib/office/foundation";
import {InvoiceCheck} from "./invoice-check";
import {InvoicePaymentControls} from './invoice-payment-controls';
import {invoiceState,invoicePaymentSection,mergeConfirmedPayments,type InvoiceEvent} from '@/lib/office/invoice-events';
import type {MacSync} from '@/lib/office/mac-sync';
import {revokeMacSync} from '@/app/actions/mac-sync';
import {useState,useTransition} from 'react';
import {useRouter} from 'next/navigation';
import {importOfficeInvoiceSnapshot} from '@/app/actions/invoice-snapshot';
import {supplierGroupKey,type InvoiceSnapshot} from '@/lib/office/invoice-snapshot';
const money=(v:number|null)=>v===null?'Unknown':new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD'}).format(v/100);
export function InvoiceRegister({snapshot,events,today,sync,data}:{data:OfficeData;snapshot:InvoiceSnapshot|null;events:InvoiceEvent[];today:string;sync:MacSync}){
 const params=useSearchParams();const [periodMode,setPeriodMode]=useState(()=>params.has('from')&&!params.get('payday')?'all':'payrun');const [payday,setPayday]=useState(()=>{const p=params.get('payday');return p&&validDate(p)?p:upcomingPayday(today);});const period=payrunPeriod(payday);
 const router=useRouter();const [search,setSearch]=useState('');const [kind,setKind]=useState('invoice');const [status,setStatus]=useState('all');const [pending,start]=useTransition();const [notice,setNotice]=useState('');
 const [paymentSection,setPaymentSection]=useState<'to-pay'|'paid'|'archived'>(()=>params.get('payments')==='paid'?'paid':'to-pay');
 const [confirmed,setConfirmed]=useState<InvoiceEvent[]>([]);
 const [paymentNotice,setPaymentNotice]=useState<{text:string;paid:boolean}|null>(null);
 const effectiveEvents=mergeConfirmedPayments(events,confirmed);
 const scopedDocs=(snapshot?.documents??[]).filter(d=>(paymentSection==='archived'||periodMode==='all'||(periodMode==='unknown'&&!invoicePeriod(d.workPeriod))||(periodMode==='payrun'&&period&&invoiceInPayrun(d,period.from,period.to)))&&(kind==='all'||(kind==='other'?d.recordType!=='invoice':d.recordType===kind))&&[d.name,d.abn,d.invoiceNumber,d.workPeriod].join(' ').toLowerCase().includes(search.toLowerCase()));
 const digest=snapshot?.sourceDigest??'';
 const archiveCount=(snapshot?.documents??[]).filter(d=>invoicePaymentSection(d,digest,effectiveEvents)==='archived').length;
 const paidCount=scopedDocs.filter(d=>invoicePaymentSection(d,digest,effectiveEvents)==='paid').length;
 const docs=scopedDocs.filter(d=>invoicePaymentSection(d,digest,effectiveEvents)===paymentSection&&(paymentSection!=='to-pay'||status==='all'||invoiceState(d,digest,effectiveEvents).status===status));
 function paymentRecorded(payment:InvoiceEvent){
  setConfirmed(rows=>mergeConfirmedPayments(rows,[payment]));
  const doc=snapshot?.documents.find(d=>d.id===payment.document_id);
  const paid=!!doc&&invoicePaymentSection(doc,digest,mergeConfirmedPayments(effectiveEvents,[payment]))==='paid';
  setPaymentNotice({paid,text:paid?(doc?.invoiceNumber||'Invoice')+' moved to Paid invoices.':'Part-payment recorded. The remaining balance stays in To pay.'});
 }
 const groups=new Map<string,typeof docs>();for(const d of docs){const key=supplierGroupKey(d);groups.set(key,[...(groups.get(key)??[]),d]);}
 async function upload(file:File){if(file.size>3_000_000){setNotice('File is too large. Maximum 3 MB.');return;}const content=await file.text();start(async()=>{try{const result=await importOfficeInvoiceSnapshot(content);setNotice(result.message);if(result.ok)router.refresh();}catch{setNotice('Import failed. The previous snapshot remains available.');}});}
 return <section className="ember-panel"><h2>Contractor payments</h2><div className="office-payrun-filters"><label>View<select aria-label="Invoice period view" value={periodMode} onChange={e=>setPeriodMode(e.target.value)}><option value="payrun">Payment period</option><option value="all">All dates / one-off work</option><option value="unknown">Missing work period</option></select></label><label>Payday<input aria-label="Payday" type="date" value={payday} onChange={e=>setPayday(e.target.value)}/></label></div>{periodMode==='payrun'&&period&&<><p>Work period: <strong>{period.from} – {period.to}</strong></p>{!isRegularPayday(payday)&&<p className="ember-notice">Outside the usual fortnightly Friday cycle. Check the selected work dates.</p>}<p className="ember-footnote">Grouped by supplier and work period, including late arrivals. This payday is a planning date; it does not mark invoices as paid. Use All dates for one-off or undated invoices.</p><PayrunSummary data={data} documents={snapshot?.documents??[]} from={period.from} to={period.to} payday={payday}/></>}<InvoiceCheck/><p className="muted">{snapshot?`${snapshot.documents.length} source documents · snapshot exported ${new Date(snapshot.exportedAt).toLocaleString('en-AU',{timeZone:'Australia/Perth'})} (UTC+8)`:'No Mac snapshot imported yet.'}</p><p className="ember-footnote">Saved invoice register · New Gmail imports currently need your connected Mac. Payments save online immediately; local files sync later. Unknown does not mean unpaid.</p>
 <details><summary>Mac connection</summary>{sync.devices.map(device=><div key={device.id}><p>{device.name} · {device.revoked?'Disconnected':device.last_seen?`Last connected ${new Date(device.last_seen).toLocaleString('en-AU',{timeZone:'Australia/Perth'})}`:'Not connected yet'}</p>{!device.revoked&&<button disabled={pending} onClick={()=>{if(window.confirm('Disconnect this Mac? File synchronization will stop until it is reconnected.'))start(async()=>{const r=await revokeMacSync(device.id);setNotice(r.message);router.refresh();});}}>Disconnect Mac</button>}</div>)}{sync.devices.filter(d=>!d.revoked).map(d=><div key={'health-'+d.id} className="ember-notice"><strong>{d.health?.status==='error'?'Sync needs attention':d.health?.last_success_at&&Date.now()-Date.parse(d.health.last_success_at)<900000?'File sync up to date':'Waiting for successful file sync'}</strong><p>Last successful sync: {d.health?.last_success_at?new Date(d.health.last_success_at).toLocaleString('en-AU',{timeZone:'Australia/Perth'}):'Not reported'}</p>{d.health?.status==='error'&&<p>{d.health.error_type} · {d.health.stage}. Retrying while Mac is online.</p>}{!!d.health?.blocked&&<p>{d.health.blocked} file actions need attention.</p>}{!!d.health?.archive_errors&&<p>{d.health.archive_errors} historical copies could not be verified.</p>}</div>)}{sync.devices.some(d=>!d.revoked&&d.health?.backup_error)&&<p className="ember-notice">Recovery backup needs attention. Payments remain saved online.</p>}<button onClick={()=>router.refresh()}>Refresh sync status</button></details><details><summary>Import a saved Mac export manually</summary><p className="ember-footnote">Choose Reports/Office_snapshot.json from your invoice assistant folder. This imports metadata only.</p><input type="file" accept=".json,application/json" aria-label="Import Mac invoice snapshot" disabled={pending} onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f);e.target.value='';}}/></details>{notice&&<p role="status" className="ember-notice">{notice}</p>}
 <div className="office-payment-sections" role="group" aria-label="Invoice payment sections"><button type="button" aria-pressed={paymentSection==='to-pay'} onClick={()=>setPaymentSection('to-pay')}>To pay <span>{scopedDocs.filter(d=>invoicePaymentSection(d,digest,effectiveEvents)==='to-pay').length}</span></button><button type="button" aria-pressed={paymentSection==='paid'} onClick={()=>setPaymentSection('paid')}>Paid invoices <span>{paidCount}</span></button><button type="button" aria-pressed={paymentSection==='archived'} onClick={()=>setPaymentSection('archived')}>Historical archive <span>{archiveCount}</span></button></div>
 {paymentNotice&&<div className="office-payment-toast"><p role="status">{paymentNotice.text}</p>{paymentNotice.paid&&paymentSection!=='paid'&&<button type="button" onClick={()=>setPaymentSection('paid')}>View paid invoices</button>}<button type="button" aria-label="Dismiss payment notification" onClick={()=>setPaymentNotice(null)}>×</button></div>}
 <div className="ember-chips"><input aria-label="Search supplier invoices" placeholder="Name, ABN, invoice or work period" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="Document type" value={kind} onChange={e=>setKind(e.target.value)}><option value="invoice">Contractor invoices</option><option value="other">Other / test documents</option><option value="all">All source documents</option></select>{paymentSection==='to-pay'&&<select aria-label="Payment status" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All awaiting payment</option><option value="Unknown">Payment not confirmed</option><option value="Part-paid">Part-paid</option></select>}</div><p className="muted">{docs.length} documents · {groups.size} supplier identity groups</p>
 {[...groups.entries()].sort((a,b)=>a[1][0].name.localeCompare(b[1][0].name)).map(([key,items])=><details className="ember-panel" key={key}><summary><strong>{items[0].name||'Unconfirmed supplier'}</strong> · ABN {items[0].abn||'unconfirmed'} · {items.length} documents</summary>{items.sort((a,b)=>b.received.localeCompare(a.received)).map(d=><article className="ember-person" key={d.id}><div className="ember-section-heading"><h3>{d.invoiceNumber||'Invoice number missing'}</h3><strong>{d.currency==='AUD'?money(d.amountCents):`${d.amountCents===null?'Unknown':d.amountCents/100} ${d.currency||'Currency unknown'}`}</strong></div><p>Work period: {d.workPeriod||'Unknown'}</p><p className="muted">Invoice date: {d.issueDate||'Unknown'} · Received: {d.received||'Unknown'}</p><p className="muted">Tonnage on source: {d.tonnage||'Not stated'} · GST on source: {d.gst||'Not stated'}</p><InvoicePaymentControls document={d} digest={snapshot!.sourceDigest} events={effectiveEvents} onPaymentRecorded={paymentRecorded} today={today} receipts={sync.receipts} readiness={paymentReadiness(d,data,snapshot!.documents,snapshot!.sourceDigest,effectiveEvents)} reviewContent={<InvoiceReconciliation document={d} data={data} documents={snapshot!.documents}/>}/>{d.paidCents!==0&&<p>Payments in Mac snapshot: {money(d.paidCents)}</p>}{d.payments.map(p=><p className="ember-footnote" key={p.id}>{p.date} · {money(p.amountCents)}</p>)}{d.duplicateOf&&<p className="error">Duplicate of {d.duplicateOf} — do not pay both.</p>}{!d.historicalClosure&&d.flags.length>0&&<ul className="ember-footnote">{d.flags.map((f,i)=><li key={i}>• {f}</li>)}</ul>}<p className="ember-footnote">{d.email} {d.phone}</p><p className="ember-footnote">{d.filename}</p>{d.source&&<a className="ember-link" href={d.source} target="_blank" rel="noreferrer">Open source email ↗</a>}</article>)}</details>)}{!docs.length&&<p className="ember-empty">{paymentSection==='archived'?'No historical documents match this search.':paymentSection==='paid'?'No paid invoices match these filters.':'No invoices awaiting payment match these filters.'}</p>}
 </section>;
}
