'use client';
import {useCallback,useEffect,useRef,useState,useTransition} from 'react';
import {listInvoiceMail,prepareInvoiceMail,approveInvoiceMail,cancelInvoiceMail} from '@/app/actions/invoice-mail';
import type {InvoiceMail,MailCapability} from '@/lib/office/invoice-mail';
import type {ClientDraft} from '@/lib/office/client-drafts';
export function InvoiceEmail({draft}:{draft:ClientDraft}){const [open,setOpen]=useState(false);return <section className="ember-panel"><button className="ember-link" onClick={()=>setOpen(!open)}>{open?'Close email panel':'Email invoice · review & send'}</button>{open&&<EmailPanel draft={draft}/>}</section>;}
function EmailPanel({draft:d}:{draft:ClientDraft}){
 const [mails,setMails]=useState<InvoiceMail[]>([]),[cap,setCap]=useState<MailCapability>({ready:false}),[subject,setSubject]=useState('Still Partners invoice '+d.invoice_number),[body,setBody]=useState('Hello,\n\nPlease find attached invoice '+d.invoice_number+' for '+d.period_start+' to '+d.period_end+', together with the work summary.\n\nKind regards,\nStill Partners'),[notice,setNotice]=useState(''),[pending,start]=useTransition();const request=useRef('');
 const refresh=useCallback(async()=>{try{const r=await listInvoiceMail(d.id);setMails(r.mails);setCap(r.capability);}catch{setNotice('Email status unavailable. Refresh before taking another action.');}},[d.id]);
 useEffect(()=>{void refresh();const timer=setInterval(()=>void refresh(),15000);return()=>clearInterval(timer);},[refresh]);
 function run(action:()=>Promise<{ok:boolean;message:string}>){start(async()=>{try{const r=await action();setNotice(r.message);await refresh();}catch{setNotice('Could not confirm the change. Refresh before retrying.');}});}
 const active=mails.some(m=>['queued','sending','sent','unknown'].includes(m.status));
 return <><h3>Review client email</h3><p>From: work@stillpartners.net</p><p className="ember-footnote">{cap.ready?'Mac reports Gmail sending permission configured. It must remain awake and online.':'Gmail sending permission is not configured. You can prepare previews; approved mail waits for the connection.'}{cap.checkedAt&&' Last checked '+new Date(cap.checkedAt).toLocaleString('en-AU',{timeZone:'Australia/Perth'})}</p>
 {!active&&<form onSubmit={e=>{e.preventDefault();if(!request.current)request.current=crypto.randomUUID();run(()=>prepareInvoiceMail({id:request.current,invoiceId:d.id,subject,body}));}}><label>Subject<input required maxLength={200} disabled={pending} value={subject} onChange={e=>{setSubject(e.target.value);request.current='';}}/></label><label>Message<textarea required rows={7} maxLength={8000} disabled={pending} value={body} onChange={e=>{setBody(e.target.value);request.current='';}}/></label><button disabled={pending} type="submit">Prepare exact email preview</button></form>}
 <button className="ember-link" onClick={()=>void refresh()}>Refresh email status</button>{notice&&<p role="status">{notice}</p>}
 {mails.map(m=><MailCard key={m.id} mail={m} blocked={active} pending={pending} run={run}/>)}<p className="ember-footnote">Only the email you approve is queued. Original contractor PDFs stay on your Mac. These generated client invoice PDFs are saved privately for your approval and delivery history.</p></>;
}
function MailCard({mail:m,blocked,pending,run}:{mail:InvoiceMail;blocked:boolean;pending:boolean;run:(a:()=>Promise<{ok:boolean;message:string}>)=>void}){
 const [reviewed,setReviewed]=useState(false);
 return <article className="ember-person"><p><strong>{m.status.toUpperCase()}</strong> · {new Date(m.created_at).toLocaleString('en-AU',{timeZone:'Australia/Perth'})}</p><p><strong>To:</strong> {m.recipient}</p><p><strong>Subject:</strong> {m.subject}</p><p style={{whiteSpace:'pre-wrap'}}>{m.body}</p><div className="ember-chips"><a href={'/api/office/invoice-mail/'+m.id+'/attachment'} target="_blank" rel="noopener noreferrer">Open exact invoice PDF</a><a href={'/api/office/invoice-mail/'+m.id+'/attachment?summary=1'} target="_blank" rel="noopener noreferrer">Open exact work summary PDF</a></div>
 {m.status==='preview'&&<><label><input type="checkbox" checked={reviewed} disabled={pending||blocked} onChange={e=>setReviewed(e.target.checked)}/> I approve this recipient, message and both PDF attachments for sending.</label><button className="ember-primary" disabled={pending||blocked||!reviewed} onClick={()=>run(()=>approveInvoiceMail(m.id,m.content_digest))}>Approve & send</button></>}
 {['preview','queued','blocked','failed'].includes(m.status)&&<button disabled={pending} onClick={()=>run(()=>cancelInvoiceMail(m.id))}>Cancel email</button>}
 {m.status==='queued'&&<p>Waiting for your Mac and Gmail sending permission. You may cancel while it is still queued.</p>}{m.status==='sending'&&<p>Sending started. Please wait for confirmation.</p>}{m.message&&<p>{m.message}</p>}
 {(m.status==='sent'||m.status==='unknown')&&<a href={m.gmail_id?'https://mail.google.com/mail/u/work@stillpartners.net/#sent/'+encodeURIComponent(m.gmail_id):'https://mail.google.com/mail/u/work@stillpartners.net/#search/'+encodeURIComponent('in:sent rfc822msgid:office-'+m.id+'@stillpartners.net')} target="_blank" rel="noopener noreferrer">Check Gmail Sent ↗</a>}{m.status==='unknown'&&<p className="error">Do not resend automatically. Delivery is uncertain; verify Gmail Sent and the recipient before correcting.</p>}</article>;
}
