"use client";
import {InvoiceCheck} from "./invoice-check";
import {InvoicePaymentControls} from './invoice-payment-controls';
import {invoiceState,type InvoiceEvent} from '@/lib/office/invoice-events';
import type {MacSync} from '@/lib/office/mac-sync';
import {revokeMacSync} from '@/app/actions/mac-sync';
import {useState,useTransition} from 'react';
import {useRouter} from 'next/navigation';
import {importOfficeInvoiceSnapshot} from '@/app/actions/invoice-snapshot';
import {supplierGroupKey,type InvoiceSnapshot} from '@/lib/office/invoice-snapshot';
const money=(v:number|null)=>v===null?'Unknown':new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD'}).format(v/100);
export function InvoiceRegister({snapshot,events,today,sync}:{snapshot:InvoiceSnapshot|null;events:InvoiceEvent[];today:string;sync:MacSync}){
 const router=useRouter();const [search,setSearch]=useState('');const [kind,setKind]=useState('invoice');const [status,setStatus]=useState('all');const [pending,start]=useTransition();const [notice,setNotice]=useState('');
 const docs=(snapshot?.documents??[]).filter(d=>(kind==='all'||(kind==='other'?d.recordType!=='invoice':d.recordType===kind))&&(status==='all'||invoiceState(d,snapshot?.sourceDigest??'',events).status===status)&&[d.name,d.abn,d.invoiceNumber,d.workPeriod].join(' ').toLowerCase().includes(search.toLowerCase()));
 const groups=new Map<string,typeof docs>();for(const d of docs){const key=supplierGroupKey(d);groups.set(key,[...(groups.get(key)??[]),d]);}
 async function upload(file:File){if(file.size>900_000){setNotice('File is too large. Maximum 900 KB.');return;}const content=await file.text();start(async()=>{try{const result=await importOfficeInvoiceSnapshot(content);setNotice(result.message);if(result.ok)router.refresh();}catch{setNotice('Import failed. The previous snapshot remains available.');}});}
 return <section className="ember-panel"><h2>Contractor invoice register</h2><InvoiceCheck/><p className="muted">{snapshot?`${snapshot.documents.length} source documents · snapshot exported ${new Date(snapshot.exportedAt).toLocaleString('en-AU',{timeZone:'Australia/Perth'})} (UTC+8)`:'No Mac snapshot imported yet.'}</p><p className="ember-notice">This is a saved Mac snapshot, not a live Gmail check. Original files stay on your Mac. Office approvals and payment records are available below. Your Mac checks for approved actions every 5 minutes while awake and connected. File sync is confirmed separately from payment status. Unknown payment status does not mean unpaid.</p>
 <details><summary>Mac connection</summary>{sync.devices.map(device=><div key={device.id}><p>{device.name} · {device.revoked?'Disconnected':device.last_seen?`Last connected ${new Date(device.last_seen).toLocaleString('en-AU',{timeZone:'Australia/Perth'})}`:'Not connected yet'}</p>{!device.revoked&&<button disabled={pending} onClick={()=>{if(window.confirm('Disconnect this Mac? File synchronization will stop until it is reconnected.'))start(async()=>{const r=await revokeMacSync(device.id);setNotice(r.message);router.refresh();});}}>Disconnect Mac</button>}</div>)}<button onClick={()=>router.refresh()}>Refresh sync status</button></details><details><summary>Import a saved Mac export manually</summary><p className="ember-footnote">Choose Reports/Office_snapshot.json from your invoice assistant folder. This imports metadata only.</p><input type="file" accept=".json,application/json" aria-label="Import Mac invoice snapshot" disabled={pending} onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f);e.target.value='';}}/></details>{notice&&<p role="status" className="ember-notice">{notice}</p>}
 <div className="ember-chips"><input aria-label="Search supplier invoices" placeholder="Name, ABN, invoice or work period" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="Document type" value={kind} onChange={e=>setKind(e.target.value)}><option value="invoice">Contractor invoices</option><option value="other">Other / test documents</option><option value="all">All source documents</option></select><select aria-label="Payment status" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All payment statuses</option><option value="Unknown">Unknown</option><option value="Paid">Paid</option><option value="Part-paid">Part-paid</option></select></div><p className="muted">{docs.length} documents · {groups.size} supplier identity groups</p>
 {[...groups.entries()].sort((a,b)=>a[1][0].name.localeCompare(b[1][0].name)).map(([key,items])=><details className="ember-panel" key={key}><summary><strong>{items[0].name||'Unconfirmed supplier'}</strong> · ABN {items[0].abn||'unconfirmed'} · {items.length} documents</summary>{items.sort((a,b)=>b.received.localeCompare(a.received)).map(d=><article className="ember-person" key={d.id}><div className="ember-section-heading"><h3>{d.invoiceNumber||'Invoice number missing'}</h3><strong>{d.currency==='AUD'?money(d.amountCents):`${d.amountCents===null?'Unknown':d.amountCents/100} ${d.currency||'Currency unknown'}`}</strong></div><p>Work period: {d.workPeriod||'Unknown'}</p><p className="muted">Invoice date: {d.issueDate||'Unknown'} · Received: {d.received||'Unknown'}</p><p className="muted">Tonnage on source: {d.tonnage||'Not stated'} · GST on source: {d.gst||'Not stated'}</p><InvoicePaymentControls document={d} digest={snapshot!.sourceDigest} events={events} today={today} receipts={sync.receipts}/>{d.paidCents!==0&&<p>Payments in Mac snapshot: {money(d.paidCents)}</p>}{d.payments.map(p=><p className="ember-footnote" key={p.id}>{p.date} · {money(p.amountCents)}</p>)}{d.duplicateOf&&<p className="error">Duplicate of {d.duplicateOf} — do not pay both.</p>}{d.flags.length>0&&<ul className="ember-footnote">{d.flags.map((f,i)=><li key={i}>• {f}</li>)}</ul>}<p className="ember-footnote">{d.email} {d.phone}</p><p className="ember-footnote">{d.filename}</p>{d.source&&<a className="ember-link" href={d.source} target="_blank" rel="noreferrer">Open source email ↗</a>}</article>)}</details>)}{!docs.length&&<p className="ember-empty">No matching documents.</p>}
 </section>;
}
