'use client';
import {useCallback,useEffect,useRef,useState,useTransition} from 'react';
import {useRouter} from 'next/navigation';
import {latestInvoiceCheck,requestInvoiceCheck} from '@/app/actions/invoice-check';
export function InvoiceCheck(){
 const router=useRouter(),[job,setJob]=useState<Awaited<ReturnType<typeof latestInvoiceCheck>>>(null),[notice,setNotice]=useState(''),[pending,start]=useTransition(),requestId=useRef(''),completed=useRef('');
 const refresh=useCallback(async()=>{try{const current=await latestInvoiceCheck();setJob(current);if(current?.status==='done'&&completed.current!==current.id){completed.current=current.id;router.refresh();}}catch{setNotice('Could not load the latest check. Refresh to try again.');}},[router]);
 useEffect(()=>{void refresh();const timer=setInterval(()=>void refresh(),10000);return()=>clearInterval(timer);},[refresh]);
 const busy=job?.status==='queued'||job?.status==='running';
 return <section className="ember-panel"><div className="ember-section-heading"><h2>Latest invoices</h2><button className="ember-primary" disabled={pending||busy} onClick={()=>{if(!requestId.current)requestId.current=crypto.randomUUID();start(async()=>{try{const result=await requestInvoiceCheck(requestId.current);setNotice(result.message);if(result.ok){requestId.current='';await refresh();}}catch{setNotice('Request could not be confirmed. Retry is safe.');}});}}>{pending?'Requesting…':job?.status==='queued'?'Waiting for Mac…':job?.status==='running'?'Checking Gmail…':'Check latest invoices'}</button></div><p className="muted">Checks incoming and self-addressed invoice emails, including late arrivals and corrections. Source documents stay on your Mac.</p>{job?.response?.reply&&<p role="status">{String(job.response.reply)}</p>}{Array.isArray(job?.response?.reviewLinks)&&job.response.reviewLinks.length>0&&<details><summary>Review flagged invoice emails ({job.response.reviewLinks.length} of {job.response.reviewCount})</summary><ol>{job.response.reviewLinks.filter((v:unknown)=>typeof v==='string'&&v.startsWith('https://mail.google.com/')).map((link:string,index:number)=><li key={link+index}><a className="ember-link" href={link} target="_blank" rel="noopener noreferrer">Open flagged email {index+1} ↗</a></li>)}</ol>{job.response.reviewCount>job.response.reviewLinks.length&&<p>Remaining review links are retained in the Gmail report on your Mac.</p>}</details>}{job?.finished_at&&<p className="ember-footnote">Last result: {new Intl.DateTimeFormat('en-AU',{dateStyle:'medium',timeStyle:'short',timeZone:'Australia/Perth'}).format(new Date(job.finished_at))}</p>}{busy&&<p role="status">{job?.status==='queued'?'This request will start when your Mac is awake, online and available.':'The Mac is checking all matching result pages and importing supported invoice files.'}</p>}{notice&&<p role="status">{notice}</p>}<button className="ember-link" onClick={()=>void refresh()}>Refresh status</button></section>;
}
