'use client';
import {useState,useTransition} from 'react';
import {useRouter} from 'next/navigation';
import {recordOfficeInvoiceEvent} from '@/app/actions/invoice-events';
import {invoiceState,type InvoiceEvent} from '@/lib/office/invoice-events';
import type {InvoiceSnapshot} from '@/lib/office/invoice-snapshot';
const aud=(n:number)=>new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD'}).format(n/100);
export function InvoicePaymentControls({document:d,digest,events,today}:{document:InvoiceSnapshot['documents'][number];digest:string;events:InvoiceEvent[];today:string}){
 const state=invoiceState(d,digest,events),router=useRouter();const [pending,start]=useTransition(),[mode,setMode]=useState<'approve'|'payment'|'void'|null>(null),[target,setTarget]=useState<string|null>(null),[amount,setAmount]=useState(''),[day,setDay]=useState(today),[reason,setReason]=useState(''),[confirmed,setConfirmed]=useState(false),[notice,setNotice]=useState(''),[requestId,setRequestId]=useState('');
 function open(kind:'approve'|'payment'|'void',id:string|null=null){setMode(kind);setTarget(id);setAmount(((d.amountCents??0)-state.paid)/100+'');setDay(today);setReason('');setConfirmed(false);setNotice('');setRequestId(crypto.randomUUID());}
 function submit(){if(!mode)return;let cents:number|null=null;if(mode==='payment'){if(!/^\d+(\.\d{1,2})?$/.test(amount)){setNotice('Enter AUD with at most two decimal places.');return;}cents=Math.round(Number(amount)*100);}const value={id:requestId,documentId:d.id,digest,kind:mode,amount:cents,day:mode==='payment'?day:null,reason,target};start(async()=>{try{const result=await recordOfficeInvoiceEvent(value);setNotice(result.message);if(result.ok){setMode(null);router.refresh();}}catch{setNotice('Could not confirm. Keep this form and retry with the same details, or refresh to check history.');}});}
 return <div><p><strong>{state.status}</strong> · Recorded payments {aud(state.paid)} · {state.approved?'Details approved':'Details need approval'}</p>{state.pending&&<p className="ember-notice">Mac sync pending. File organization has not been confirmed.</p>}<div className="ember-chips">{!state.approved&&<button disabled={pending||!!d.duplicateOf||d.recordType!=='invoice'} onClick={()=>open('approve')}>Approve invoice</button>}<button disabled={pending||!state.approved||!!d.duplicateOf||d.recordType!=='invoice'||d.amountCents===null||state.paid>=d.amountCents} onClick={()=>open('payment')}>Record payment / Paid</button></div>
 {state.payments.map(p=><p key={p.id} className="ember-footnote">{p.payment_date} · {aud(p.amount_cents??0)} · {p.reason} {!d.payments.some(x=>x.id===p.id)&&<button disabled={pending} className="ember-text-button" onClick={()=>open('void',p.id)}>Correct / cancel payment</button>}</p>)}
 {mode&&<div className="ember-panel"><h3>{mode==='approve'?'Confirm invoice details':mode==='payment'?'Record an actual payment':'Cancel this Office payment'}</h3><p>{d.name} · {d.invoiceNumber} · {d.workPeriod}</p>{mode==='payment'&&<><label>Amount paid (AUD)<input type="text" inputMode="decimal" value={amount} disabled={pending} onChange={e=>{setAmount(e.target.value);setRequestId(crypto.randomUUID());}}/></label><label>Actual payment date<input type="date" value={day} max={today} disabled={pending} onChange={e=>{setDay(e.target.value);setRequestId(crypto.randomUUID());}}/></label><p className="ember-footnote">Historical payment coverage may be incomplete. Check your bank record before confirming. This button records a payment; it does not transfer money.</p></>}<label>{mode==='payment'?'Bank reference / payment confirmation':mode==='approve'?'Review evidence / reason':'Correction reason'}<input value={reason} disabled={pending} maxLength={2000} onChange={e=>{setReason(e.target.value);setRequestId(crypto.randomUUID());}}/></label><label><input type="checkbox" checked={confirmed} disabled={pending} onChange={e=>setConfirmed(e.target.checked)}/>{mode==='payment'?' I confirm I paid this exact invoice on the date and for the amount above.':mode==='approve'?' I checked the supplier, ABN, buyer, amount, work period, version and all review warnings.':' I confirm this payment entry was incorrect. Keep its audit history.'}</label><div className="ember-chips"><button disabled={pending||!confirmed||reason.trim().length<3} onClick={submit}>{pending?'Saving…':'Confirm'}</button><button disabled={pending} onClick={()=>setMode(null)}>Cancel</button></div></div>}{notice&&<p role="status" className="ember-notice">{notice}</p>}</div>;
}
