'use client';
import {useEffect,useRef,useState} from 'react';
import {listSitePlans,missingWorkPlans,saveSitePlan} from '@/app/actions/site-plans';
import {directory,type OfficeData} from '@/lib/office/foundation';
import {addIsoDays} from '@/lib/operations/dates';
import {pendingPeople,type PlanRead,type SitePlan,type SitePlanInput} from '@/lib/office/site-plans';
export type PlanSelection={id:string;day:string;people:string[];nonce:number};
export function PlanAttention({open}:{open:(day:string)=>void}){
 const [data,setData]=useState<PlanRead|null>(null),[error,setError]=useState(false);
 useEffect(()=>{let alive=true,busy=false;const refresh=async()=>{if(busy||document.hidden)return;busy=true;try{const r=await missingWorkPlans();if(alive){setData(r);setError(false);}}catch{if(alive)setError(true);}finally{busy=false;}};void refresh();const t=setInterval(()=>void refresh(),60000);document.addEventListener('visibilitychange',refresh);window.addEventListener('office-work-saved',refresh);return()=>{alive=false;clearInterval(t);document.removeEventListener('visibilitychange',refresh);window.removeEventListener('office-work-saved',refresh);};},[]);
 if(error)return <aside className="ember-notice" role="status">Hours reminder status could not refresh. <button onClick={()=>open('')}>Open site plans</button></aside>;
 if(!data?.plans.length||!data.enabled)return null;
 const count=data.plans.reduce((n,p)=>n+p.missing,0);
 return <aside className="ember-notice office-mail-attention" role="status"><strong>Bobby · {count} work {count===1?'record needs':'records need'} hours</strong><p>{data.plans[0].workDate} · {data.plans[0].site}: {pendingPeople(data.plans[0]).map(p=>p.shortName||p.fullName).join(', ')}</p><button className="ember-primary" onClick={()=>open(data.plans[0].workDate)}>Enter missing hours →</button>{data.scanError&&<p>Background check needs attention. These gaps are from current saved plans.</p>}</aside>;
}
export function SitePlans({data,today,dateRequest,addresses,openWork,openSites}:{data:OfficeData;today:string;dateRequest:{day:string;nonce:number}|null;addresses:Record<string,string>;openWork:(s:PlanSelection)=>void;openSites:()=>void}){
 const [day,setDay]=useState(addIsoDays(today,1)),[loaded,setLoaded]=useState<PlanRead|null>(null),[site,setSite]=useState(''),[selected,setSelected]=useState<string[]>([]),[time,setTime]=useState('17:00'),[note,setNote]=useState(''),[search,setSearch]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const attempt=useRef<{key:string;id:string}|null>(null),generation=useRef(0),editing=useRef(false);
 const plan=loaded?.plans.find(p=>p.jobId===site),dirty=site&&JSON.stringify([selected.slice().sort(),time,note])!==JSON.stringify([(plan?.people.filter(p=>p.active).map(p=>p.id)||[]).sort(),plan?.reminderTime||'17:00',plan?.note||'']);
 editing.current=!!dirty;
 function loadPlan(p?:SitePlan){setSelected(p?.people.filter(x=>x.active).map(x=>x.id)||[]);setTime(p?.reminderTime||'17:00');setNote(p?.note||'');setNotice('');}
 useEffect(()=>{if(dateRequest&&(!editing.current||window.confirm('Discard unsaved plan changes?'))){setDay(dateRequest.day||today);setSite('');loadPlan();}},[dateRequest,today]);
 useEffect(()=>{let alive=true;const seq=++generation.current;setLoading(true);setLoaded(null);setError('');void listSitePlans(day).then(r=>{if(alive&&seq===generation.current)setLoaded(r);}).catch(()=>{if(alive)setError('Plans could not load. Retry before making changes.');}).finally(()=>{if(alive)setLoading(false);});return()=>{alive=false;};},[day]);
 useEffect(()=>{let alive=true;const updated=()=>{if(editing.current)return;void listSitePlans(day).then(r=>{if(alive)setLoaded(r);}).catch(()=>{});};window.addEventListener('office-work-saved',updated);return()=>{alive=false;window.removeEventListener('office-work-saved',updated);};},[day]);
 useEffect(()=>{const before=(e:BeforeUnloadEvent)=>{if(editing.current){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',before);return()=>window.removeEventListener('beforeunload',before);},[]);
 async function refresh(){setLoading(true);try{const r=await listSitePlans(day);setLoaded(r);loadPlan(r.plans.find(p=>p.jobId===site));setError('');}catch{setError('Plans could not refresh. Your changes are retained.');}finally{setLoading(false);}}
 async function save(){if(!loaded||busy)return;setBusy(true);setNotice('');const input:Omit<SitePlanInput,'eventId'>={jobId:site,workDate:day,reminderTime:time,workerIds:selected,expectedVersion:plan?.version||0,note};const key=JSON.stringify(input);if(attempt.current?.key!==key)attempt.current={key,id:crypto.randomUUID()};try{const r=await saveSitePlan({...input,eventId:attempt.current.id});if(r.ok){attempt.current=null;await refresh();window.dispatchEvent(new Event('office-work-saved'));}setNotice(r.message);}catch{setNotice('Save could not be confirmed. Retry safely; your selection is retained.');}finally{setBusy(false);}}
 function choose(p:OfficeData['projects'][number]){if(dirty&&!window.confirm('Discard unsaved plan changes?'))return;setSite(p.id);loadPlan(loaded?.plans.find(x=>x.jobId===p.id));}
 const visible=data.projects.filter(p=>p.active||loaded?.plans.some(x=>x.jobId===p.id));
 const people=directory(data.contractors,search).filter(p=>p.active||plan?.people.some(x=>x.id===p.id));
 return <section className="office-site-plans"><div className="ember-section-heading"><h2>Site plans</h2><label>Date<input aria-label="Plan date" type="date" min="2026-09-29" max={addIsoDays(today,366)} disabled={busy} value={day} onChange={e=>{if(!e.target.value||dirty&&!window.confirm('Discard unsaved plan changes?'))return;setSite('');loadPlan();setDay(e.target.value);}}/></label></div><div className="ember-chips"><button disabled={busy} onClick={()=>{if(dirty&&!window.confirm('Discard unsaved plan changes?'))return;setSite('');loadPlan();setDay(today);}}>Today</button><button disabled={busy} onClick={()=>{if(dirty&&!window.confirm('Discard unsaved plan changes?'))return;setSite('');loadPlan();setDay(addIsoDays(today,1));}}>Tomorrow</button><button disabled={busy||loading} onClick={()=>{if(!dirty||window.confirm('Discard changes and reload?'))void refresh();}}>Refresh</button><button onClick={openSites}>Add / manage sites</button></div>
 <p className="muted">Choose the site, then the people. Bobby asks for missing hours after the reminder time.</p>{loading&&<p role="status">Loading plans…</p>}{error&&<p role="alert" className="error">{error}</p>}
 <div className="ember-site-grid">{visible.map(p=>{const existing=loaded?.plans.find(x=>x.jobId===p.id);return <button key={p.id} className={`ember-site ${site===p.id?'selected':''}`} disabled={busy||loading||!loaded} aria-pressed={site===p.id} onClick={()=>choose(p)}><span className="client-label">{data.clients.find(c=>c.id===p.clientId)?.name}</span><strong>{p.name}</strong><small>{addresses[p.id]}</small><small>{existing?`${existing.people.filter(x=>x.active).length} planned · ${existing.missing} hours needed`:'No plan yet'}</small></button>;})}</div>
 {site&&loaded&&<section className="ember-panel"><h3>{data.projects.find(p=>p.id===site)?.name}</h3><p>{addresses[site]}</p><label>Ask for hours after · Perth time<input type="time" value={time} disabled={busy} onChange={e=>setTime(e.target.value)}/></label><label>Find a contractor<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Full name or short name…"/></label>
 <div className="office-plan-people">{people.map(p=>{const current=plan?.people.find(x=>x.id===p.id),other=loaded.plans.find(x=>x.jobId!==site&&x.people.some(v=>v.id===p.id&&v.active));return <label key={p.id}><input type="checkbox" disabled={busy||!!other} checked={selected.includes(p.id)} onChange={e=>setSelected(ids=>e.target.checked?[...ids,p.id]:ids.filter(x=>x!==p.id))}/><span><strong>{p.shortName||p.fullName}</strong>{p.shortName&&<small>{p.fullName}</small>}<small>{other?`Planned at ${other.site}`:current?.entryId?`${current.hours}h recorded`:selected.includes(p.id)?'Planned · hours not recorded':current?'Removed / did not attend':''}</small></span></label>;})}</div>
 <details><summary>Add note (optional)</summary><textarea maxLength={1000} value={note} disabled={busy} onChange={e=>setNote(e.target.value)} /></details><p className="ember-footnote">Uncheck someone who will not attend. To move them, save their removal here and select them at the new site. Existing actual hours are kept.</p><button className="ember-primary" disabled={busy||loading||!time||(!dirty&&!!plan)||(!plan&&!selected.length)} onClick={()=>void save()}>{busy?'Saving…':'Save plan'}</button>
 {plan&&day<=today&&<button className="ember-primary" disabled={busy||!!dirty} onClick={()=>openWork({id:site,day,people:pendingPeople(plan).map(p=>p.id),nonce:Date.now()})}>Enter hours · {plan.missing} missing</button>}
 {plan?.people.some(p=>p.active&&p.otherSites.length)&&<p className="ember-notice">Some people already have records at another site. Check the site/date before entering more hours.</p>}
 </section>}{notice&&<p role="status" className="ember-notice">{notice}</p>}<p className="ember-footnote">{loaded?.enabled===false?'Automatic reminders are paused in Company → Work inbox. ':'In-app reminders are checked on the server every five minutes, including while your Mac is off. '}Phone push is not enabled. Saving a plan never creates hours, an invoice or a payment.</p></section>;
}
