'use client';
import {useRef,useState} from 'react';
import {searchWorkMail,readWorkMail} from '@/app/actions/work-mail';
type Page=Awaited<ReturnType<typeof searchWorkMail>>;
export function WorkMail({connected}:{connected:boolean}){
 const [query,setQuery]=useState('newer_than:14d'),[executed,setExecuted]=useState(''),[page,setPage]=useState<Page|null>(null),[mail,setMail]=useState<Awaited<ReturnType<typeof readWorkMail>>|null>(null),[pending,setPending]=useState(false),[notice,setNotice]=useState('');const reader=useRef<HTMLElement>(null);
 async function search(more=false){setPending(true);setNotice('');try{const q=more?executed:query,r=await searchWorkMail(q,more?page?.nextPageToken:'');setExecuted(q);setPage(p=>({...r,items:more?[...(p?.items??[]),...r.items.filter(i=>!p?.items.some(x=>x.id===i.id))]:r.items}));if(!more)setMail(null);}catch{setNotice('Gmail search did not finish. Check the connection and retry. No complete search is confirmed.');}finally{setPending(false);}}
 async function read(id:string){setPending(true);try{setMail(await readWorkMail(id));setTimeout(()=>reader.current?.scrollIntoView({block:'start',behavior:'smooth'}),0);}catch{setNotice('This message could not be read. Try its original Gmail link.');}finally{setPending(false);}}
 return <><h1>Work Gmail</h1><p className="muted">Search and read directly, including Sent and self-addressed mail. No AI API or Mac is used for these controls.</p>{!connected?<section className="ember-panel"><h2>Gmail connection needed</h2><p>The phone app needs its own read-only Google connection. Your Mac connection remains separate.</p><a className="ember-link" href="/office/connections">Open connections →</a></section>:<><form className="ember-panel" onSubmit={e=>{e.preventDefault();void search();}}><label>Search Gmail<input value={query} maxLength={1000} placeholder="Name, invoice, has:attachment…" onChange={e=>setQuery(e.target.value)} disabled={pending}/></label><div className="ember-chips"><button type="button" disabled={pending} onClick={()=>setQuery('newer_than:14d')}>Recent mail</button><button type="button" disabled={pending} onClick={()=>setQuery('newer_than:14d (invoice OR has:attachment)')}>Invoices & files</button><button type="button" disabled={pending} onClick={()=>setQuery('in:sent newer_than:14d')}>Sent</button></div><button type="submit" className="ember-primary" disabled={pending||!query.trim()}>{pending?'Reading Gmail…':'Search'}</button></form>
 {notice&&<p role="alert" className="ember-notice">{notice}</p>}{page&&<><p>{page.items.length} messages loaded · Checked {new Date(page.checkedAt).toLocaleString('en-AU',{timeZone:'Australia/Perth'})}</p>{page.items.map(m=><article key={m.id} className="ember-panel"><strong>{m.subject||'(No subject)'}</strong><p>{m.from}</p><small>{new Date(m.receivedAt).toLocaleString('en-AU',{timeZone:'Australia/Perth'})} · {m.labels.includes('SENT')?'Sent':'Incoming / other'}</small><div className="ember-chips"><button disabled={pending} onClick={()=>void read(m.id)}>Read message</button><a href={m.source} target="_blank" rel="noopener noreferrer">Open in Gmail ↗</a></div></article>)}{page.nextPageToken?<button disabled={pending} onClick={()=>void search(true)}>Load next page</button>:<p>All matching result pages loaded. Attachments are not automatically analysed.</p>}</>}
 {mail&&<section ref={reader} className="ember-panel"><h2>{mail.subject}</h2><p>From: {mail.from}<br/>To: {mail.to}</p><p style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{mail.bodyFormat==='html'?mail.body.replace(/<style\b[^>]*>[\s\S]*?<\/style>|<script\b[^>]*>[\s\S]*?<\/script>/gi,'').replace(/<[^>]*>/g,' ').replace(/&nbsp;/g,' '):mail.body}</p>{mail.bodyTruncated&&<p>Message truncated. Open Gmail for the complete body.</p>}<h3>Attachments · {mail.attachments.length}</h3>{mail.attachments.map((a,i)=><p key={i}>{a.filename||'Inline image'} · {Math.ceil(a.bytes/1024)} KB · <a className="ember-link" href={`/api/office/gmail/attachment?id=${encodeURIComponent(mail.id)}&part=${encodeURIComponent(a.partId)}`}>Download</a></p>)}<p className="ember-footnote">Originals remain in Gmail. Downloading does not register an invoice or confirm a payment.</p><button onClick={()=>void navigator.clipboard.writeText(mail.source).then(()=>setNotice('Source link copied. Add it in Company → Documents.')).catch(()=>setNotice('Could not copy. Use the Open in Gmail link.'))}>Copy source link</button></section>}</>}
 </>;
}
