import ts from 'typescript';
import {readFileSync,writeFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const modules=['foundation','tonnage','reconciliation'];
let result='// Generated by npm run build:office-tools. Shared with the Office UI.\n"use strict";\nconst factories={\n';
for(const name of modules){
 const input=readFileSync(path.join(root,'lib/office',name+'.ts'),'utf8');
 const code=ts.transpileModule(input,{compilerOptions:{target:ts.ScriptTarget.ES2020,module:ts.ModuleKind.CommonJS,importsNotUsedAsValues:ts.ImportsNotUsedAsValues.Remove}}).outputText;
 result+=JSON.stringify(name)+':function(require,module,exports){\n'+code+'\n},\n';
}
result+='};\nconst cache={};\nfunction localRequire(id){const name=id.split("/").pop();if(!factories[name])throw new Error("Unsupported module");if(!cache[name]){const m={exports:{}};cache[name]=m;factories[name](localRequire,m,m.exports);}return cache[name].exports;}\n';
result+='const input=JSON.parse(require("node:fs").readFileSync(0,"utf8"));\nif(!Array.isArray(input.snapshot?.documents)||!Array.isArray(input.data?.contractors))throw new Error("Missing company records");\nconst doc=input.snapshot.documents.find(d=>d.id===input.documentId);\nif(!doc)throw new Error("Invoice not found");\nprocess.stdout.write(JSON.stringify(localRequire("reconciliation").reconcileInvoice(doc,input.data,input.snapshot.documents)));\n';
writeFileSync(path.join(root,'scripts/office_reconciliation.cjs'),result);
