// Generated by npm run build:office-tools. Shared with the Office UI.
"use strict";
const factories={
"foundation":function(require,module,exports){
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.contactText = contactText;
exports.directory = directory;
exports.effectiveRate = effectiveRate;
exports.hoursAmountCents = hoursAmountCents;
exports.validAbn = validAbn;
exports.validDate = validDate;
function contactText(person) {
    return `Full Name: ${person.fullName}\nPhone: ${person.phone || "Not provided"}\nEmail: ${person.email || "Not provided"}`;
}
function directory(people, query = "") {
    const term = query.trim().toLocaleLowerCase();
    return people.filter(p => `${p.fullName} ${p.phone} ${p.email} ${p.abn}`.toLocaleLowerCase().includes(term))
        .sort((a, b) => Number(b.active) - Number(a.active) || Number(a.group === "occasional") - Number(b.group === "occasional") || a.fullName.localeCompare(b.fullName, "en-AU"));
}
function effectiveRate(rates, workerId, clientId, kind, day) {
    const candidates = rates.filter(r => !r.voidedAt && r.workerId === workerId && r.kind === kind && r.effectiveFrom <= day && (r.clientId === clientId || (kind === "contractor" && r.clientId === null)));
    // A client-specific agreement takes precedence over the contractor's base rate.
    return candidates.sort((a, b) => Number(b.clientId === clientId) - Number(a.clientId === clientId) || b.effectiveFrom.localeCompare(a.effectiveFrom))[0] ?? null;
}
function hoursAmountCents(hours, rateCents) {
    if (!Number.isFinite(hours) || hours < 0 || hours > 24 || Math.abs(hours * 100 - Math.round(hours * 100)) > 1e-7 || !Number.isSafeInteger(rateCents) || rateCents <= 0)
        throw new Error("Invalid hours or hourly rate");
    return Math.round(Math.round(hours * 100) * rateCents / 100);
}
function validAbn(input) {
    const abn = input.replace(/\s/g, "");
    if (!/^\d{11}$/.test(abn))
        return false;
    const digits = abn.split("").map(Number);
    digits[0] -= 1;
    return digits.reduce((sum, value, index) => sum + value * [10, 1, 3, 5, 7, 9, 11, 13, 15, 17, 19][index], 0) % 89 === 0;
}
function validDate(value) {
    return /^\d{4}-\d{2}-\d{2}$/.test(value) && !Number.isNaN(Date.parse(value + "T00:00:00Z")) && new Date(value + "T00:00:00Z").toISOString().slice(0, 10) === value;
}

},
"tonnage":function(require,module,exports){
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.BILLING_HOURS_PER_TONNE = void 0;
exports.sourceTonnes = sourceTonnes;
exports.tonnesRateCents = tonnesRateCents;
exports.rateTimeline = rateTimeline;
const foundation_1 = require("./foundation");
exports.BILLING_HOURS_PER_TONNE = 10;
function sourceTonnes(raw) {
    const text = raw.trim().replace(/\s*(?:tonnes?|tons?|t)\s*$/i, '').trim();
    if (!/^(?:\d+|\d{1,3}(?:,\d{3})+)(?:\.\d{1,4})?$/.test(text))
        return null;
    const value = Number(text.replaceAll(',', ''));
    return Number.isFinite(value) && value > 0 && value <= 1000000 ? value : null;
}
function tonnesRateCents(hourlyRateCents) {
    if (!Number.isSafeInteger(hourlyRateCents) || hourlyRateCents <= 0 || hourlyRateCents > 10000000)
        throw new Error('Invalid agreed hourly rate');
    return hourlyRateCents * exports.BILLING_HOURS_PER_TONNE;
}
function rateTimeline(data, workerId, from, to) {
    if (!(0, foundation_1.validDate)(from) || !(0, foundation_1.validDate)(to) || from > to)
        return [];
    return data.entries.filter(e => e.workerId === workerId && e.workDate >= from && e.workDate <= to).sort((a, b) => a.workDate.localeCompare(b.workDate) || a.id.localeCompare(b.id)).map(e => {
        const site = data.projects.find(p => p.id === e.jobId);
        const rate = site ? (0, foundation_1.effectiveRate)(data.rates, workerId, site.clientId, 'contractor', e.workDate) : null;
        return { entryId: e.id, workDate: e.workDate, siteId: e.jobId, clientId: site?.clientId ?? null, payableHours: e.contractorHours,
            billingTonnes: e.contractorHours === null ? null : e.contractorHours / exports.BILLING_HOURS_PER_TONNE,
            hourlyRateCents: rate?.hourlyRateCents ?? null, tonneRateCents: rate ? tonnesRateCents(rate.hourlyRateCents) : null,
            rateId: rate?.id ?? null, effectiveFrom: rate?.effectiveFrom ?? null };
    });
}

},
"reconciliation":function(require,module,exports){
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.invoicePeriod = invoicePeriod;
exports.reconcileInvoice = reconcileInvoice;
const foundation_1 = require("./foundation");
const tonnage_1 = require("./tonnage");
const norm = (s) => s.trim().replace(/\s+/g, ' ').toLocaleLowerCase('en-AU');
const abn = (s) => s.replace(/\s/g, '');
function invoicePeriod(raw) {
    const text = raw.trim();
    const iso = text.match(/^(\d{4}-\d{2}-\d{2})\s*(?:to|[-–—])\s*(\d{4}-\d{2}-\d{2})$/i);
    const au = text.match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})\s*(?:to|[-–—])\s*(\d{1,2})\/(\d{1,2})\/(\d{4})$/i);
    const from = iso?.[1] ?? (au ? `${au[3]}-${au[2].padStart(2, '0')}-${au[1].padStart(2, '0')}` : text);
    const to = iso?.[2] ?? (au ? `${au[6]}-${au[5].padStart(2, '0')}-${au[4].padStart(2, '0')}` : text);
    if (!(0, foundation_1.validDate)(from) || !(0, foundation_1.validDate)(to) || from > to)
        return null;
    return { from, to };
}
function gstCents(raw) {
    const v = raw.trim().replace(/^\$\s*/, '');
    if (!/^(?:\d+|\d{1,3}(?:,\d{3})+)(?:\.\d{1,2})?$/.test(v))
        return null;
    const value = Number(v.replaceAll(',', ''));
    return Number.isFinite(value) && value >= 0 ? Math.round(value * 100) : null;
}
function reconcileInvoice(d, data, all) {
    const result = { status: 'review', message: 'Review required', expectedFeeCents: null, expectedTotalCents: null, differenceCents: null, actualHours: null, payableHours: null, rows: 0, sourceTonnes: null, expectedBillingTonnes: null, tonneRates: [], period: invoicePeriod(d.workPeriod), issues: [] };
    const issue = (text) => { result.issues.push(text); return result; };
    if (d.recordType !== 'invoice' || d.currency !== 'AUD' || d.amountCents === null || d.amountCents <= 0 || d.duplicateOf)
        return issue('Only a positive AUD contractor invoice with no duplicate link can be compared.');
    if (!(0, foundation_1.validAbn)(d.abn) || abn(d.abn) === '62687072420')
        return issue('Supplier ABN requires review.');
    const matches = data.contractors.filter(p => abn(p.abn) === abn(d.abn) && norm(p.fullName) === norm(d.name));
    if (matches.length !== 1)
        return issue('Link one contractor with the same full name and supplier ABN before comparing.');
    const period = result.period;
    if (!period)
        return issue('A valid work period is required; invoice or received dates are not substituted.');
    if (period.from < data.from || period.to > data.to)
        return issue('Load this work period in Office to compare its time records.');
    if (all.some(x => x.id !== d.id && x.recordType === 'invoice' && !x.duplicateOf && abn(x.abn) === abn(d.abn) && norm(x.name) !== norm(d.name)))
        result.issues.push('This supplier ABN appears under another name; resolve the identity conflict.');
    if (all.some(x => { if (x.id === d.id || x.recordType !== 'invoice' || x.duplicateOf || abn(x.abn) !== abn(d.abn) || norm(x.name) !== norm(d.name))
        return false; const p = invoicePeriod(x.workPeriod); return p && p.from <= period.to && p.to >= period.from; }))
        result.issues.push('Another invoice overlaps this work period. Check revisions or split invoices before payment.');
    const entries = data.entries.filter(e => e.workerId === matches[0].id && e.workDate >= period.from && e.workDate <= period.to);
    result.rows = entries.length;
    if (!entries.length)
        return issue('No time records found for this contractor and period. Missing records do not mean zero work.');
    result.tonneRates = (0, tonnage_1.rateTimeline)(data, matches[0].id, period.from, period.to);
    result.actualHours = 0;
    result.payableHours = 0;
    let expected = 0, missing = false;
    for (const e of entries) {
        const project = data.projects.find(p => p.id === e.jobId);
        const rate = project ? (0, foundation_1.effectiveRate)(data.rates, e.workerId, project.clientId, 'contractor', e.workDate) : null;
        const hours = e.contractorHours;
        result.actualHours += e.actualHours;
        if (hours === null) {
            missing = true;
            result.issues.push(`Payable hours need confirmation on ${e.workDate}.`);
            continue;
        }
        result.payableHours += hours;
        if (hours > 0 && !rate) {
            missing = true;
            result.issues.push(`Agreed contractor rate needed on ${e.workDate}.`);
            continue;
        }
        try {
            if (hours > 0)
                expected += (0, foundation_1.hoursAmountCents)(hours, rate.hourlyRateCents);
        }
        catch {
            missing = true;
            result.issues.push(`Invalid hours or rate on ${e.workDate}.`);
        }
    }
    result.actualHours = Math.round(result.actualHours * 100) / 100;
    result.payableHours = Math.round(result.payableHours * 100) / 100;
    result.expectedBillingTonnes = result.payableHours / tonnage_1.BILLING_HOURS_PER_TONNE;
    if (d.tonnage?.trim()) {
        result.sourceTonnes = (0, tonnage_1.sourceTonnes)(d.tonnage);
        if (result.sourceTonnes === null)
            result.issues.push('Source tonnage is invalid or ambiguous.');
        else if (Math.abs(result.sourceTonnes - result.expectedBillingTonnes) > 0.00005)
            result.issues.push('Invoice billing tonnes differ from recorded payable hours divided by 10.');
    }
    if (missing) {
        result.issues = [...new Set(result.issues)];
        return result;
    }
    result.expectedFeeCents = expected;
    const gst = gstCents(d.gst);
    if (gst === null)
        return issue('GST amount is not explicit on the imported source. Do not assume it is zero.');
    if (gst > d.amountCents)
        return issue('GST exceeds the invoice total.');
    if (gst !== 0 && gst !== Math.round(expected / 10))
        result.issues.push('Source GST does not equal 10% of the recorded fee; review the GST basis.');
    result.expectedTotalCents = expected + gst;
    result.differenceCents = d.amountCents - result.expectedTotalCents;
    if (d.flags.length)
        result.issues.push('Source document flags still need review.');
    if (result.issues.length)
        return result;
    result.status = result.differenceCents === 0 ? 'match' : 'difference';
    result.message = result.status === 'match' ? 'Amount matches the recorded payable hours and rates effective on each work date.' + (result.sourceTonnes !== null ? ' Billing tonnes also match the recorded payable hours.' : ' Source tonnage was not available for a quantity comparison.') : 'Invoice total differs from the recorded calculation.';
    return result;
}

},
};
const cache={};
function localRequire(id){const name=id.split("/").pop();if(!factories[name])throw new Error("Unsupported module");if(!cache[name]){const m={exports:{}};cache[name]=m;factories[name](localRequire,m,m.exports);}return cache[name].exports;}
const input=JSON.parse(require("node:fs").readFileSync(0,"utf8"));
if(!Array.isArray(input.snapshot?.documents)||!Array.isArray(input.data?.contractors))throw new Error("Missing company records");
const doc=input.snapshot.documents.find(d=>d.id===input.documentId);
if(!doc)throw new Error("Invoice not found");
process.stdout.write(JSON.stringify(localRequire("reconciliation").reconcileInvoice(doc,input.data,input.snapshot.documents)));
