begin;
create temp table direct_checks(name text,passed boolean);
do $$
declare actor uuid=gen_random_uuid();other_actor uuid=gen_random_uuid();task_id uuid=gen_random_uuid();doc_id uuid=gen_random_uuid();file_id uuid=gen_random_uuid();device uuid=gen_random_uuid();token text=repeat('synthetic-device-',4);r jsonb;again jsonb;lease uuid;before_payments bigint;
begin
 insert into auth.users(id,email) values(actor,'direct-test@example.invalid'),(other_actor,'direct-other@example.invalid');
 insert into public.profiles(id,role,full_name,is_active) values(actor,'admin','Synthetic direct test',true),(other_actor,'worker','Synthetic other',true) on conflict(id) do update set role=excluded.role,is_active=true;
 perform set_config('request.jwt.claim.sub','',true);perform set_config('request.jwt.claims','{}',true);
 select count(*) into before_payments from public.office_invoice_events;
 insert into public.office_assistant_tasks(id,user_id,prompt,context,executor) values(task_id,actor,'Synthetic read','{"directRequest":{"kind":"contacts"}}','direct');
 r=public.office_direct_exchange(actor,jsonb_build_object('action','claim','id',task_id));lease=(r->>'lease_id')::uuid;
 if lease is null then raise exception 'Missing lease';end if;
 if public.office_direct_exchange(actor,jsonb_build_object('action','claim','id',task_id))<>'{}'::jsonb then raise exception 'Duplicate claim';end if;
 if public.office_direct_exchange(actor,jsonb_build_object('action','complete','id',task_id,'lease_id',gen_random_uuid(),'status','done','response',jsonb_build_object('action','none','reply','read only')))->>'ok'<>'false' then raise exception 'Stale lease accepted';end if;
 begin perform public.office_direct_exchange(actor,jsonb_build_object('action','complete','id',task_id,'lease_id',lease,'status','done','response',jsonb_build_object('action','create_client')));raise exception 'TEST FAILED mutation result accepted';exception when others then if sqlerrm like 'TEST FAILED%' then raise;end if;end;
 insert into direct_checks values('one claim; stale lease and apply-able result rejected',true);
 r=public.office_direct_exchange(actor,jsonb_build_object('action','complete','id',task_id,'lease_id',lease,'status','done','response',jsonb_build_object('action','none','reply','read only')));
 if r->>'ok'<>'true' then raise exception 'Read result not saved';end if;
 if public.office_direct_exchange(actor,jsonb_build_object('action','claim','id',task_id))<>'{}'::jsonb then raise exception 'Completed read replayed';end if;
 begin perform public.office_direct_exchange(other_actor,jsonb_build_object('action','claim','id',task_id));raise exception 'TEST FAILED worker allowed';exception when others then if sqlerrm like 'TEST FAILED%' then raise;end if;end;
 if has_function_privilege('authenticated','public.office_direct_exchange(uuid,jsonb)','EXECUTE') or has_function_privilege('anon','public.office_document_file_exchange(uuid,jsonb)','EXECUTE') then raise exception 'Privileged RPC exposed';end if;
 insert into direct_checks values('result persisted without changes; completion cannot be replayed; worker/browser executor denied',true);
 insert into public.office_documents(id,title,entity_type,category,source_note,status,created_by,updated_by) values(doc_id,'Synthetic file','company','other','Synthetic original','active',actor,actor);
 r=public.office_document_file_exchange(actor,jsonb_build_object('action','reserve','id',file_id,'documentId',doc_id,'filename','synthetic.txt','mime','text/plain','bytes',3,'sha256',repeat('a',64)));
 again=public.office_document_file_exchange(actor,jsonb_build_object('action','reserve','id',gen_random_uuid(),'documentId',doc_id,'filename','copy.txt','mime','text/plain','bytes',3,'sha256',repeat('a',64)));
 if again->>'id'<>file_id::text or r->>'status'<>'pending' then raise exception 'File dedupe/reservation failed';end if;
 begin perform public.office_document_file_exchange(actor,jsonb_build_object('action','reserve','id',file_id,'documentId',doc_id,'filename','changed.txt','mime','text/plain','bytes',4,'sha256',repeat('b',64)));raise exception 'TEST FAILED upload identity reused';exception when others then if sqlerrm like 'TEST FAILED%' then raise;end if;end;
 insert into direct_checks values('file dedupe; stable reservation; content mismatch rejected',true);
 insert into office_private.mac_devices(id,name,token_hash,owner_id) values(device,'Synthetic document read',encode(extensions.digest(token,'sha256'),'hex'),actor);
 begin perform public.office_device_document_file(token,file_id);raise exception 'TEST FAILED pending file exposed';exception when others then if sqlerrm like 'TEST FAILED%' then raise;end if;end;
 perform public.office_document_file_exchange(actor,jsonb_build_object('action','complete','id',file_id,'sha256',repeat('a',64)));
 r=public.office_device_document_file(token,file_id);if r->>'sha256'<>repeat('a',64) then raise exception 'Missing ready file';end if;
 update office_private.mac_devices set revoked=true where id=device;
 begin perform public.office_device_document_file(token,file_id);raise exception 'TEST FAILED revoked device read';exception when others then if sqlerrm like 'TEST FAILED%' then raise;end if;end;
 if has_table_privilege('authenticated','public.office_document_files','INSERT') or has_table_privilege('anon','public.office_document_files','SELECT') or (select public from storage.buckets where id='office-documents') then raise exception 'File store exposed';end if;
 if not (select relrowsecurity from pg_class where oid='public.office_document_files'::regclass) then raise exception 'RLS not enabled';end if;
 insert into direct_checks values('pending invisible; ready readable; revoked device rejected; private storage and RLS',true);
 perform set_config('request.jwt.claim.sub',actor::text,true);
 execute 'set local role authenticated';
 if not exists(select 1 from public.office_document_files where id=file_id) then raise exception 'Finance admin could not read ready file';end if;
 perform set_config('request.jwt.claim.sub',other_actor::text,true);
 if exists(select 1 from public.office_document_files where id=file_id) then raise exception 'Worker could read private finance file';end if;
 execute 'reset role';
 perform set_config('request.jwt.claim.sub','',true);
 insert into direct_checks values('actual authenticated RLS permits finance and denies contractor',true);

 if (select count(*) from public.office_invoice_events)<>before_payments then raise exception 'Payment records changed';end if;
 insert into direct_checks values('no invoice approvals or payment events created',true);
end;$$;
select * from direct_checks;
rollback;
