-- Synthetic records only; always roll back. Run with the database test administrator.
begin;
create temporary table office_test_results(check_name text,passed boolean);
do $$
declare actor uuid;doc uuid=gen_random_uuid();ev uuid=gen_random_uuid();person uuid=gen_random_uuid();other uuid=gen_random_uuid();client uuid=gen_random_uuid();site uuid=gen_random_uuid();entry uuid=gen_random_uuid();v jsonb;n jsonb;source jsonb;blocked boolean;payments bigint;today date=(now() at time zone 'Australia/Perth')::date;
begin
 select id into actor from public.profiles where role::text='admin' and coalesce(is_active,true) limit 1;
 if actor is null then raise exception 'Test admin required';end if;
 perform set_config('request.jwt.claim.sub',actor::text,true);
 select count(*) into payments from public.office_invoice_events;
 insert into public.workers(id,full_name) values(person,'Synthetic Legal Person'),(other,'Synthetic Other Person');
 v=jsonb_build_object('id',doc,'expectedVersion',0,'title','Synthetic insurance','entityType','contractor','entityId',person,'category','insurance','sourceUrl','https://example.invalid/document','sourceNote','','notes','','expiresOn',today+5,'expiryConfirmed',true,'status','active');
 perform public.office_save_document(ev,v);perform public.office_save_document(ev,v);
 if (select version from public.office_documents where id=doc)<>1 or (select count(*) from public.office_document_events where document_id=doc)<>1 then raise exception 'Document replay wrote twice';end if;
 blocked=false;begin perform public.office_save_document(gen_random_uuid(),v);exception when raise_exception then blocked=true;end;if not blocked then raise exception 'Stale edit allowed';end if;
 update office_private.monitor_state set enabled=true;
 perform office_private.scan_document_expiry(actor);perform office_private.scan_document_expiry(actor);
 if (select count(*) from office_private.detected_work where issue_key='document-expiry:'||doc)<>1 then raise exception 'Expiry case missing or duplicated';end if;
 perform public.office_save_document(gen_random_uuid(),v||jsonb_build_object('expectedVersion',1,'expiresOn',today+365));
 perform office_private.scan_document_expiry(actor);
 if exists(select 1 from office_private.detected_work where issue_key='document-expiry:'||doc and active) then raise exception 'Renewal failed to clear case';end if;
 insert into office_test_results values('document replay, stale-version protection, expiry dedupe and renewal',true);
 n=jsonb_build_object('workerId',person,'fullName','Synthetic Legal Person','shortName','Synthetic Nick','aliases',jsonb_build_array('Synthetic Alias'),'expectedVersion',0);ev=gen_random_uuid();
 perform public.office_save_contractor_name(ev,n);perform public.office_save_contractor_name(ev,n);
 if (select version from public.office_contractor_names where worker_id=person)<>1 then raise exception 'Name replay wrote twice';end if;
 blocked=false;begin perform public.office_save_contractor_name(gen_random_uuid(),n||jsonb_build_object('workerId',other,'fullName','Synthetic Other Person','shortName','SYNTHETIC NICK'));exception when raise_exception then blocked=true;end;if not blocked then raise exception 'Ambiguous alias allowed';end if;
 blocked=false;begin perform public.office_save_contractor_name(gen_random_uuid(),n||jsonb_build_object('fullName','Wrong identity'));exception when raise_exception then blocked=true;end;if not blocked then raise exception 'Wrong identity allowed';end if;
 insert into office_test_results values('names replay, collision and exact legal identity guards',true);
 insert into public.clients(id,name,is_active) values(client,'Synthetic Billing Client',true);
 insert into public.jobs(id,client_id,site_name) values(site,client,'Synthetic Site');
 insert into public.work_entries(id,worker_id,job_id,work_date,hours) values(entry,other,site,today,8);
 insert into public.office_rates(worker_id,client_id,kind,hourly_rate_cents,effective_from,agreement_note,created_by) values(other,client,'client',7000,today,'Synthetic agreed rate',actor);
 blocked=false;begin perform office_private.client_draft_source(client,today,today);exception when raise_exception then blocked=true;end;if not blocked then raise exception 'Missing summary name allowed';end if;
 perform public.office_save_contractor_name(gen_random_uuid(),jsonb_build_object('workerId',other,'fullName','Synthetic Other Person','shortName','Synthetic Two','aliases','[]'::jsonb,'expectedVersion',0));
 source=office_private.client_draft_source(client,today,today);
 if source#>>'{rows,0,summaryName}'<>'Synthetic Two' or source#>>'{rows,0,fullName}'<>'Synthetic Other Person' then raise exception 'Summary/legal identity not separated';end if;
 insert into office_test_results values('client draft requires assigned short name and freezes it separately',true);
 if (select count(*) from public.office_invoice_events)<>payments then raise exception 'Financial history changed';end if;
 if has_table_privilege('anon','public.office_documents','SELECT') or has_table_privilege('authenticated','public.office_documents','UPDATE') or has_table_privilege('authenticated','public.office_contractor_names','DELETE') or has_function_privilege('anon','public.office_save_contractor_name(uuid,jsonb)','EXECUTE') then raise exception 'Unsafe privileges';end if;
 perform set_config('request.jwt.claim.sub',gen_random_uuid()::text,true);
 blocked=false;begin perform public.office_save_document(gen_random_uuid(),v);exception when raise_exception then blocked=true;end;if not blocked then raise exception 'Unauthorised document write';end if;
 blocked=false;begin perform public.office_save_contractor_name(gen_random_uuid(),n);exception when raise_exception then blocked=true;end;if not blocked then raise exception 'Unauthorised alias write';end if;
 insert into office_test_results values('finance-only RPCs, no direct writes, no financial side effects',true);
end;$$;
set local role authenticated;
do $$begin if exists(select 1 from public.office_documents) or exists(select 1 from public.office_contractor_names) then raise exception 'RLS exposed company documents or names to unrelated user';end if;end;$$;
reset role;
select * from office_test_results;
rollback;
