begin;
create temp table monitor_test_result(check_name text,passed boolean);
do $$
declare actor uuid=gen_random_uuid(); worker uuid=gen_random_uuid(); client uuid=gen_random_uuid(); job uuid=gen_random_uuid();
 digest text=encode(extensions.digest(gen_random_uuid()::text,'sha256'),'hex'); doc jsonb; item uuid; v integer; payments bigint; r jsonb;
begin
 insert into auth.users(id,email) values(actor,'monitor-test@example.invalid');
 insert into public.profiles(id,role,full_name,is_active) values(actor,'admin','Synthetic Monitor Test',true) on conflict(id) do update set role='admin',is_active=true;
 perform set_config('request.jwt.claim.sub',actor::text,true);
 perform set_config('request.jwt.claims',jsonb_build_object('sub',actor,'role','authenticated')::text,true);
 select count(*) into payments from public.office_invoice_events;
 doc=jsonb_build_object('id','synthetic-monitor','recordType','invoice','name','Example Supplier','sourceHash',repeat('a',64),'workPeriod','2026-09-21 to 2026-09-26','supplierId','example','invoiceNumber','MON-1','amountCents',10000,'paidCents',0,'payments','[]'::jsonb,'flags',jsonb_build_array('Date needs review'));
 insert into public.office_invoice_snapshots(source_digest,exported_at,imported_by,payload) values(digest,now()+interval '1 day',actor,jsonb_build_object('documents',jsonb_build_array(doc,
 doc||jsonb_build_object('id','synthetic-archived','historicalClosure',jsonb_build_object('source_hash',repeat('a',64))),doc||jsonb_build_object('id','synthetic-paid','paidCents',10000))));
 update office_private.monitor_state set enabled=false,work_from='2098-01-01';
 perform public.office_monitor_control(null,true);
 if exists(select 1 from office_private.detected_work where issue_key='invoice:synthetic-monitor') then raise exception 'Paused detector created work';end if;
 insert into monitor_test_result values('paused detector leaves work unchanged',true);
 perform public.office_monitor_control(true,true);
 select record_id into item from office_private.detected_work where issue_key='invoice:synthetic-monitor';
 if item is null then raise exception 'No invoice case created';end if;
 if exists(select 1 from office_private.detected_work where issue_key in('invoice:synthetic-archived','invoice:synthetic-paid')) then raise exception 'Historical or paid invoice reopened';end if;
 insert into monitor_test_result values('source warning creates case; archived and paid skipped',true);
 select version into v from public.office_company_records where id=item;
 perform public.office_monitor_control(null,true);
 if (select version from public.office_company_records where id=item)<>v then raise exception 'Repeated scan changed version';end if;
 insert into monitor_test_result values('unchanged repeated scan adds no case or event',true);
 -- Owner editing is represented by the same version increment used by the optimistic save RPC.
 update public.office_company_records set body='Owner notes must survive',next_action='Wait for correction',status='waiting_external',version=version+1 where id=item;
 doc=doc||jsonb_build_object('flags','[]'::jsonb);
 update public.office_invoice_snapshots set payload=jsonb_build_object('documents',jsonb_build_array(doc)) where source_digest=digest;
 perform public.office_monitor_control(null,true);
 if not exists(select 1 from public.office_company_records where id=item and body='Owner notes must survive' and status='waiting_external' and detection->>'active'='false') then raise exception 'Detector closed owner follow-up or overwrote notes';end if;
 insert into monitor_test_result values('cleared condition preserves owner notes and follow-up',true);
 doc=doc||jsonb_build_object('flags',jsonb_build_array('Changed warning'),'sourceHash',repeat('b',64));
 update public.office_invoice_snapshots set payload=jsonb_build_object('documents',jsonb_build_array(doc)) where source_digest=digest;
 perform public.office_monitor_control(null,true);
 update public.office_company_records set status='completed',outcome='Owner resolved',version=version+1 where id=item;
 perform public.office_monitor_control(null,true);
 if (select status from public.office_company_records where id=item)<>'completed' then raise exception 'Identical evidence reopened closed case';end if;
 doc=doc||jsonb_build_object('sourceHash',repeat('c',64));
 update public.office_invoice_snapshots set payload=jsonb_build_object('documents',jsonb_build_array(doc)) where source_digest=digest;
 perform public.office_monitor_control(null,true);
 if not exists(select 1 from public.office_company_records where id=item and status='needs_review' and body='Owner notes must survive') then raise exception 'Changed evidence failed to reopen safely';end if;
 insert into monitor_test_result values('closed unchanged stays closed; revised evidence reopens same case',true);
 insert into public.workers(id,full_name) values(worker,'Synthetic Rate Test');
 insert into public.clients(id,name) values(client,'Synthetic Client');
 insert into public.jobs(id,client_id,site_name) values(job,client,'Synthetic Site');
 insert into public.work_entries(worker_id,job_id,work_date,hours) values(worker,job,'2097-12-31',8);
 perform public.office_monitor_control(null,true);
 if exists(select 1 from office_private.detected_work where issue_key like 'rates:'||worker||':%') then raise exception 'Old time records reviewed';end if;
 insert into public.work_entries(worker_id,job_id,work_date,hours) values(worker,job,'2098-01-02',8);
 perform public.office_monitor_control(null,true);
 if (select count(*) from office_private.detected_work where issue_key like 'rates:'||worker||':%' and active)<>2 then raise exception 'Contractor/client missing rates not separated';end if;
 insert into monitor_test_result values('new-work cutoff and separate payable/billable rates respected',true);
 insert into public.office_rates(worker_id,kind,hourly_rate_cents,effective_from,agreement_note,created_by) values(worker,'contractor',6000,'2098-01-02','Synthetic agreed base rate',actor);
 perform public.office_monitor_control(null,true);
 if (select count(*) from office_private.detected_work where issue_key like 'rates:'||worker||':%' and active)<>1 then raise exception 'Base contractor rate did not clear only contractor case';end if;
 insert into public.office_rates(worker_id,client_id,kind,hourly_rate_cents,effective_from,agreement_note,created_by) values(worker,client,'client',7500,'2098-01-02','Synthetic agreed client rate',actor);
 perform public.office_monitor_control(null,true);
 if exists(select 1 from office_private.detected_work where issue_key like 'rates:'||worker||':%' and active) then raise exception 'Agreed rates did not clear cases';end if;
 if exists(select 1 from public.office_company_records r join office_private.detected_work l on l.record_id=r.id where l.issue_key like 'rates:'||worker||':%' and r.status<>'completed') then raise exception 'Untouched resolved rate cases not closed';end if;
 insert into monitor_test_result values('rate correction clears untouched cases without financial writes',true);
 if (select count(*) from public.office_invoice_events)<>payments then raise exception 'Detector changed payments';end if;
 insert into monitor_test_result values('all checks preserve financial event register',true);
 update office_private.monitor_state set last_checked_at=null;
 update office_private.mac_health set status=status;
 if exists(select 1 from office_private.mac_health) and not exists(select 1 from office_private.monitor_state where last_checked_at is not null and last_error is null) then raise exception 'Health trigger did not run detector';end if;
 insert into monitor_test_result values('device health publication automatically runs detector',true);
 update public.jobs set client_id=null where id=job;
 perform public.office_monitor_control(null,true);
 if not exists(select 1 from office_private.detected_work where issue_key='rates:'||worker||':unassigned:client' and active) then raise exception 'Unassigned site lost its client-rate case';end if;
 insert into monitor_test_result values('unassigned legacy site cannot abort all checks',true);
 if has_function_privilege('authenticated','office_private.scan_work(uuid)','EXECUTE') or has_function_privilege('anon','public.office_monitor_control(boolean,boolean)','EXECUTE') or has_table_privilege('authenticated','office_private.detected_work','SELECT') then raise exception 'Private detector exposed';end if;
 update public.profiles set role='operations_admin' where id=actor;
 begin
  perform public.office_monitor_control(true,true);raise exception 'FAIL non-finance caller accepted';
 exception when others then if sqlerrm like 'FAIL%' then raise;end if;end;
 insert into monitor_test_result values('private access and non-finance calls denied',true);
end $$;
select * from monitor_test_result;
rollback;
