begin;
create temp table mail_watch_test_result(check_name text,passed boolean);
do $$
declare actor uuid=gen_random_uuid(); other_actor uuid=gen_random_uuid(); device uuid=gen_random_uuid();token text=repeat('synthetic-test-',4);r jsonb;payload jsonb;item uuid;v integer;before_events bigint;
begin
 insert into auth.users(id,email) values(actor,'mail-watch-test@example.invalid');
 insert into public.profiles(id,role,full_name,is_active) values(actor,'admin','Synthetic Mail Watch',true) on conflict(id) do update set role='admin',is_active=true;
 insert into office_private.mac_devices(id,name,token_hash,owner_id) values(device,'Synthetic test',encode(extensions.digest(token,'sha256'),'hex'),actor);
 perform set_config('request.jwt.claim.sub','',true);perform set_config('request.jwt.claims','{}',true);
 update office_private.monitor_state set enabled=true;
 select count(*) into before_events from public.office_invoice_events;
 begin perform public.office_mail_watch_exchange('invalid','{"action":"status"}');raise exception 'Test failed: bad token accepted';exception when others then if sqlerrm like 'Test failed:%' then raise;end if;end;
 insert into mail_watch_test_result values('invalid token denied',true);
 payload=jsonb_build_object('action','observe','message_id','deadbeef001','thread_id','feedface001','received_at','2026-09-29T01:00:00Z','subject','Synthetic source','result',jsonb_build_object('title','Requested document','summary','A synthetic client requests evidence.','needsAttention',true,'priority','urgent','nextAction','Review the prepared response.','preparedReply','Draft only; not sent.','issues','[]'::jsonb));
 r=public.office_mail_watch_exchange(token,payload);
 select record_id into item from office_private.detected_work where issue_key='mail:feedface001';
 if item is null or not (r->>'ok')::boolean then raise exception 'Missing work item';end if;
 if not exists(select 1 from public.office_company_records where id=item and priority='urgent' and body like '%not sent%' and status='needs_review') then raise exception 'Incorrect prepared case';end if;
 select version into v from public.office_company_records where id=item;
 perform public.office_mail_watch_exchange(token,payload);
 if (select version from public.office_company_records where id=item)<>v then raise exception 'Replay modified work';end if;
 insert into mail_watch_test_result values('idempotent prepared case with priority and no sent claim',true);
 update public.office_company_records set body='Owner notes',priority='low',version=version+1,status='completed',outcome='Owner action' where id=item;
 payload=jsonb_set(payload,'{message_id}','"deadbeef002"');payload=jsonb_set(payload,'{received_at}','"2026-09-29T02:00:00Z"');
 perform public.office_mail_watch_exchange(token,payload);
 if not exists(select 1 from public.office_company_records where id=item and body='Owner notes' and priority='low' and status='needs_review') then raise exception 'New source did not preserve owner notes/priority or reopen';end if;
 select version into v from public.office_company_records where id=item;
 payload=jsonb_set(payload,'{message_id}','"deadbeef003"');payload=jsonb_set(payload,'{received_at}','"2026-09-29T00:00:00Z"');
 perform public.office_mail_watch_exchange(token,payload);
 if (select version from public.office_company_records where id=item)<>v then raise exception 'Older source overwrote newer case';end if;
 insert into mail_watch_test_result values('same thread updates; owner notes survive; older source cannot regress case',true);
 update office_private.monitor_state set enabled=false;
 payload=jsonb_set(payload,'{message_id}','"deadbeef004"');r=public.office_mail_watch_exchange(token,payload);
 if not (r->>'paused')::boolean or exists(select 1 from office_private.mail_observations where message_id='deadbeef004') then raise exception 'Pause ignored';end if;
 insert into mail_watch_test_result values('pause prevents background observation commit',true);
 update office_private.monitor_state set enabled=true;
 payload=jsonb_set(payload,'{result,needsAttention}','false');perform public.office_mail_watch_exchange(token,payload);
 if (select version from public.office_company_records where id=item)<>v then raise exception 'Informational mail incorrectly closed/changed work';end if;
 insert into mail_watch_test_result values('routine mail logged without new alert or automatic closure',true);
 perform set_config('request.jwt.claim.sub',other_actor::text,true);
 begin perform public.office_mail_watch_exchange(token,'{"action":"status"}');raise exception 'Test failed: mismatched owner accepted';exception when others then if sqlerrm like 'Test failed:%' then raise;end if;end;
 perform set_config('request.jwt.claim.sub','',true);
 update office_private.mac_devices set revoked=true where id=device;
 begin perform public.office_mail_watch_exchange(token,'{"action":"status"}');raise exception 'Test failed: revoked device accepted';exception when others then if sqlerrm like 'Test failed:%' then raise;end if;end;
 if has_table_privilege('anon','office_private.mail_observations','SELECT') or has_table_privilege('authenticated','office_private.mail_watch_state','UPDATE') then raise exception 'Private mail ledger exposed';end if;
 if (select count(*) from public.office_invoice_events)<>before_events then raise exception 'Payment records changed';end if;
 insert into mail_watch_test_result values('owner mismatch/revocation denied; private tables and financial records preserved',true);
end;$$;
select * from mail_watch_test_result;
rollback;
